/* manifest.js — GENERATED by tools/lm-corpus.mjs. Do not edit by hand.
 *
 * Who wrote what. The page reads the writer counts and character totals to
 * label the corpus picker; the rest is provenance — one line per agent, so a
 * slice that turns out to be junk can be traced back to the writer that made it
 * and regenerated on its own.
 */

export const MANIFEST = {
  "code": {
    "writers": 88,
    "characters": 653814,
    "parts": [
      {
        "id": "code-01-js",
        "language": "js",
        "characters": 8032
      },
      {
        "id": "code-02-js",
        "language": "js",
        "characters": 7256
      },
      {
        "id": "code-03-js",
        "language": "js",
        "characters": 7823
      },
      {
        "id": "code-04-js",
        "language": "js",
        "characters": 8336
      },
      {
        "id": "code-05-js",
        "language": "js",
        "characters": 9113
      },
      {
        "id": "code-06-js",
        "language": "js",
        "characters": 7516
      },
      {
        "id": "code-07-js",
        "language": "js",
        "characters": 7994
      },
      {
        "id": "code-08-js",
        "language": "js",
        "characters": 7535
      },
      {
        "id": "code-09-js",
        "language": "js",
        "characters": 6859
      },
      {
        "id": "code-10-js",
        "language": "js",
        "characters": 6078
      },
      {
        "id": "code-11-js",
        "language": "js",
        "characters": 7558
      },
      {
        "id": "code-12-js",
        "language": "js",
        "characters": 7566
      },
      {
        "id": "code-13-js",
        "language": "js",
        "characters": 8071
      },
      {
        "id": "code-14-js",
        "language": "js",
        "characters": 7230
      },
      {
        "id": "code-15-js",
        "language": "js",
        "characters": 7200
      },
      {
        "id": "code-16-js",
        "language": "js",
        "characters": 7345
      },
      {
        "id": "code-17-js",
        "language": "js",
        "characters": 7956
      },
      {
        "id": "code-18-js",
        "language": "js",
        "characters": 8134
      },
      {
        "id": "code-19-js",
        "language": "js",
        "characters": 6649
      },
      {
        "id": "code-20-js",
        "language": "js",
        "characters": 6758
      },
      {
        "id": "code-21-py",
        "language": "py",
        "characters": 9337
      },
      {
        "id": "code-22-py",
        "language": "py",
        "characters": 6193
      },
      {
        "id": "code-23-py",
        "language": "py",
        "characters": 6124
      },
      {
        "id": "code-24-py",
        "language": "py",
        "characters": 10282
      },
      {
        "id": "code-25-py",
        "language": "py",
        "characters": 8145
      },
      {
        "id": "code-26-py",
        "language": "py",
        "characters": 7960
      },
      {
        "id": "code-27-py",
        "language": "py",
        "characters": 6492
      },
      {
        "id": "code-28-py",
        "language": "py",
        "characters": 6511
      },
      {
        "id": "code-29-py",
        "language": "py",
        "characters": 7143
      },
      {
        "id": "code-30-py",
        "language": "py",
        "characters": 6247
      },
      {
        "id": "code-31-py",
        "language": "py",
        "characters": 7043
      },
      {
        "id": "code-32-py",
        "language": "py",
        "characters": 7348
      },
      {
        "id": "code-33-py",
        "language": "py",
        "characters": 6886
      },
      {
        "id": "code-34-py",
        "language": "py",
        "characters": 7554
      },
      {
        "id": "code-35-py",
        "language": "py",
        "characters": 6966
      },
      {
        "id": "code-36-py",
        "language": "py",
        "characters": 5243
      },
      {
        "id": "code-37-py",
        "language": "py",
        "characters": 5594
      },
      {
        "id": "code-38-py",
        "language": "py",
        "characters": 7606
      },
      {
        "id": "code-39-ts",
        "language": "ts",
        "characters": 7885
      },
      {
        "id": "code-40-ts",
        "language": "ts",
        "characters": 7988
      },
      {
        "id": "code-41-ts",
        "language": "ts",
        "characters": 6213
      },
      {
        "id": "code-42-ts",
        "language": "ts",
        "characters": 7362
      },
      {
        "id": "code-43-ts",
        "language": "ts",
        "characters": 7795
      },
      {
        "id": "code-44-ts",
        "language": "ts",
        "characters": 7658
      },
      {
        "id": "code-45-html",
        "language": "html",
        "characters": 7413
      },
      {
        "id": "code-46-html",
        "language": "html",
        "characters": 7603
      },
      {
        "id": "code-47-css",
        "language": "css",
        "characters": 5906
      },
      {
        "id": "code-48-css",
        "language": "css",
        "characters": 6427
      },
      {
        "id": "code-49-css",
        "language": "css",
        "characters": 6228
      },
      {
        "id": "code-50-css",
        "language": "css",
        "characters": 5611
      },
      {
        "id": "code-51-sql",
        "language": "sql",
        "characters": 6267
      },
      {
        "id": "code-52-sql",
        "language": "sql",
        "characters": 6200
      },
      {
        "id": "code-53-sql",
        "language": "sql",
        "characters": 4871
      },
      {
        "id": "code-54-sql",
        "language": "sql",
        "characters": 5624
      },
      {
        "id": "code-55-sh",
        "language": "sh",
        "characters": 5987
      },
      {
        "id": "code-56-sh",
        "language": "sh",
        "characters": 6675
      },
      {
        "id": "code-57-sh",
        "language": "sh",
        "characters": 6223
      },
      {
        "id": "code-58-sh",
        "language": "sh",
        "characters": 7212
      },
      {
        "id": "code-59-go",
        "language": "go",
        "characters": 9368
      },
      {
        "id": "code-60-go",
        "language": "go",
        "characters": 6940
      },
      {
        "id": "code-61-go",
        "language": "go",
        "characters": 8899
      },
      {
        "id": "code-62-rs",
        "language": "rs",
        "characters": 7914
      },
      {
        "id": "code-63-rs",
        "language": "rs",
        "characters": 6964
      },
      {
        "id": "code-64-rs",
        "language": "rs",
        "characters": 7408
      },
      {
        "id": "code-65-c",
        "language": "c",
        "characters": 8200
      },
      {
        "id": "code-66-c",
        "language": "c",
        "characters": 7339
      },
      {
        "id": "code-67-c",
        "language": "c",
        "characters": 7082
      },
      {
        "id": "code-68-java",
        "language": "java",
        "characters": 9369
      },
      {
        "id": "code-69-java",
        "language": "java",
        "characters": 7230
      },
      {
        "id": "code-70-java",
        "language": "java",
        "characters": 7788
      },
      {
        "id": "code-71-json",
        "language": "json",
        "characters": 5114
      },
      {
        "id": "code-72-yaml",
        "language": "yaml",
        "characters": 6153
      },
      {
        "id": "code-73-docker",
        "language": "docker",
        "characters": 5858
      },
      {
        "id": "code-74-md",
        "language": "md",
        "characters": 6837
      },
      {
        "id": "code-75-diff",
        "language": "diff",
        "characters": 6404
      },
      {
        "id": "pro-001",
        "language": "pro",
        "characters": 9059
      },
      {
        "id": "pro-002",
        "language": "pro",
        "characters": 8979
      },
      {
        "id": "pro-003",
        "language": "pro",
        "characters": 8943
      },
      {
        "id": "pro-004",
        "language": "pro",
        "characters": 8890
      },
      {
        "id": "pro-005",
        "language": "pro",
        "characters": 8990
      },
      {
        "id": "pro-006",
        "language": "pro",
        "characters": 9067
      },
      {
        "id": "pro-007",
        "language": "pro",
        "characters": 8989
      },
      {
        "id": "pro-008",
        "language": "pro",
        "characters": 8753
      },
      {
        "id": "pro-009",
        "language": "pro",
        "characters": 7647
      },
      {
        "id": "pro-010",
        "language": "pro",
        "characters": 8797
      },
      {
        "id": "pro-011",
        "language": "pro",
        "characters": 9048
      },
      {
        "id": "pro-012",
        "language": "pro",
        "characters": 9603
      },
      {
        "id": "pro-013",
        "language": "pro",
        "characters": 9177
      }
    ]
  },
  "general": {
    "writers": 48,
    "characters": 331453,
    "parts": [
      {
        "id": "gen-01",
        "language": "gen",
        "characters": 7020
      },
      {
        "id": "gen-02",
        "language": "gen",
        "characters": 7818
      },
      {
        "id": "gen-03",
        "language": "gen",
        "characters": 8071
      },
      {
        "id": "gen-04",
        "language": "gen",
        "characters": 7452
      },
      {
        "id": "gen-05",
        "language": "gen",
        "characters": 8558
      },
      {
        "id": "gen-06",
        "language": "gen",
        "characters": 7788
      },
      {
        "id": "gen-07",
        "language": "gen",
        "characters": 7185
      },
      {
        "id": "gen-08",
        "language": "gen",
        "characters": 7275
      },
      {
        "id": "gen-09",
        "language": "gen",
        "characters": 5977
      },
      {
        "id": "gen-10",
        "language": "gen",
        "characters": 5042
      },
      {
        "id": "gen-11",
        "language": "gen",
        "characters": 7751
      },
      {
        "id": "gen-12",
        "language": "gen",
        "characters": 7895
      },
      {
        "id": "gen-13",
        "language": "gen",
        "characters": 6599
      },
      {
        "id": "gen-14",
        "language": "gen",
        "characters": 7704
      },
      {
        "id": "gen-15",
        "language": "gen",
        "characters": 4470
      },
      {
        "id": "gen-16",
        "language": "gen",
        "characters": 4291
      },
      {
        "id": "gen-17",
        "language": "gen",
        "characters": 6726
      },
      {
        "id": "gen-18",
        "language": "gen",
        "characters": 7974
      },
      {
        "id": "gen-19",
        "language": "gen",
        "characters": 5431
      },
      {
        "id": "gen-20",
        "language": "gen",
        "characters": 7903
      },
      {
        "id": "gen-21",
        "language": "gen",
        "characters": 7876
      },
      {
        "id": "gen-22",
        "language": "gen",
        "characters": 7169
      },
      {
        "id": "gen-23",
        "language": "gen",
        "characters": 7048
      },
      {
        "id": "gen-24",
        "language": "gen",
        "characters": 8079
      },
      {
        "id": "gen-25",
        "language": "gen",
        "characters": 6119
      },
      {
        "id": "heb-01",
        "language": "heb",
        "characters": 7701
      },
      {
        "id": "heb-02",
        "language": "heb",
        "characters": 4725
      },
      {
        "id": "heb-03",
        "language": "heb",
        "characters": 7230
      },
      {
        "id": "heb-04",
        "language": "heb",
        "characters": 7522
      },
      {
        "id": "heb-05",
        "language": "heb",
        "characters": 8595
      },
      {
        "id": "heb-06",
        "language": "heb",
        "characters": 5199
      },
      {
        "id": "heb-07",
        "language": "heb",
        "characters": 7535
      },
      {
        "id": "heb-08",
        "language": "heb",
        "characters": 6195
      },
      {
        "id": "heb-09",
        "language": "heb",
        "characters": 6287
      },
      {
        "id": "heb-10",
        "language": "heb",
        "characters": 6790
      },
      {
        "id": "know-001",
        "language": "know",
        "characters": 6011
      },
      {
        "id": "know-002",
        "language": "know",
        "characters": 4882
      },
      {
        "id": "know-003",
        "language": "know",
        "characters": 6612
      },
      {
        "id": "know-004",
        "language": "know",
        "characters": 6282
      },
      {
        "id": "know-005",
        "language": "know",
        "characters": 7079
      },
      {
        "id": "know-006",
        "language": "know",
        "characters": 7190
      },
      {
        "id": "know-007",
        "language": "know",
        "characters": 6599
      },
      {
        "id": "know-008",
        "language": "know",
        "characters": 6409
      },
      {
        "id": "know-009",
        "language": "know",
        "characters": 6024
      },
      {
        "id": "know-010",
        "language": "know",
        "characters": 7394
      },
      {
        "id": "know-011",
        "language": "know",
        "characters": 6348
      },
      {
        "id": "know-012",
        "language": "know",
        "characters": 7481
      },
      {
        "id": "know-013",
        "language": "know",
        "characters": 10048
      }
    ]
  },
  "chat": {
    "writers": 8,
    "characters": 34810,
    "parts": [
      {
        "id": "chat-01",
        "language": "chat",
        "characters": 3297
      },
      {
        "id": "chat-02",
        "language": "chat",
        "characters": 4127
      },
      {
        "id": "chat-03",
        "language": "chat",
        "characters": 4448
      },
      {
        "id": "chat-04",
        "language": "chat",
        "characters": 4606
      },
      {
        "id": "chat-05",
        "language": "chat",
        "characters": 5337
      },
      {
        "id": "chat-06",
        "language": "chat",
        "characters": 5029
      },
      {
        "id": "chat-07",
        "language": "chat",
        "characters": 3970
      },
      {
        "id": "chat-08",
        "language": "chat",
        "characters": 3982
      }
    ]
  },
  "pictures": {
    "writers": 21,
    "characters": 127225,
    "parts": [
      {
        "id": "art-01",
        "language": "art",
        "characters": 5199
      },
      {
        "id": "art-02",
        "language": "art",
        "characters": 5457
      },
      {
        "id": "art-03",
        "language": "art",
        "characters": 5743
      },
      {
        "id": "art-04",
        "language": "art",
        "characters": 4644
      },
      {
        "id": "art-05",
        "language": "art",
        "characters": 4702
      },
      {
        "id": "art-06",
        "language": "art",
        "characters": 5032
      },
      {
        "id": "see-01",
        "language": "see",
        "characters": 6431
      },
      {
        "id": "see-02",
        "language": "see",
        "characters": 5233
      },
      {
        "id": "see-03",
        "language": "see",
        "characters": 6717
      },
      {
        "id": "see-04",
        "language": "see",
        "characters": 5020
      },
      {
        "id": "see-05",
        "language": "see",
        "characters": 7836
      },
      {
        "id": "see-06",
        "language": "see",
        "characters": 6432
      },
      {
        "id": "see-07",
        "language": "see",
        "characters": 6010
      },
      {
        "id": "see-08",
        "language": "see",
        "characters": 4632
      },
      {
        "id": "see-09",
        "language": "see",
        "characters": 5211
      },
      {
        "id": "svg-01",
        "language": "svg",
        "characters": 7118
      },
      {
        "id": "svg-02",
        "language": "svg",
        "characters": 6217
      },
      {
        "id": "svg-03",
        "language": "svg",
        "characters": 7032
      },
      {
        "id": "svg-04",
        "language": "svg",
        "characters": 6511
      },
      {
        "id": "svg-05",
        "language": "svg",
        "characters": 8122
      },
      {
        "id": "svg-06",
        "language": "svg",
        "characters": 7886
      }
    ]
  }
};
