/* manifest.js — GENERATED by tools/lm-corpus.mjs. Do not edit by hand.
 *
 * Who wrote what. The page reads the writer counts and character totals to
 * label the corpus picker; the rest is provenance — one line per agent, so a
 * slice that turns out to be junk can be traced back to the writer that made it
 * and regenerated on its own.
 */

export const MANIFEST = {
  "code": {
    "writers": 75,
    "characters": 537846,
    "parts": [
      {
        "id": "code-01-js",
        "language": "js",
        "characters": 8032
      },
      {
        "id": "code-02-js",
        "language": "js",
        "characters": 7256
      },
      {
        "id": "code-03-js",
        "language": "js",
        "characters": 7823
      },
      {
        "id": "code-04-js",
        "language": "js",
        "characters": 8336
      },
      {
        "id": "code-05-js",
        "language": "js",
        "characters": 9113
      },
      {
        "id": "code-06-js",
        "language": "js",
        "characters": 7516
      },
      {
        "id": "code-07-js",
        "language": "js",
        "characters": 7994
      },
      {
        "id": "code-08-js",
        "language": "js",
        "characters": 7535
      },
      {
        "id": "code-09-js",
        "language": "js",
        "characters": 6859
      },
      {
        "id": "code-10-js",
        "language": "js",
        "characters": 6078
      },
      {
        "id": "code-11-js",
        "language": "js",
        "characters": 7558
      },
      {
        "id": "code-12-js",
        "language": "js",
        "characters": 7566
      },
      {
        "id": "code-13-js",
        "language": "js",
        "characters": 8071
      },
      {
        "id": "code-14-js",
        "language": "js",
        "characters": 7230
      },
      {
        "id": "code-15-js",
        "language": "js",
        "characters": 7200
      },
      {
        "id": "code-16-js",
        "language": "js",
        "characters": 7345
      },
      {
        "id": "code-17-js",
        "language": "js",
        "characters": 7956
      },
      {
        "id": "code-18-js",
        "language": "js",
        "characters": 8134
      },
      {
        "id": "code-19-js",
        "language": "js",
        "characters": 6649
      },
      {
        "id": "code-20-js",
        "language": "js",
        "characters": 6758
      },
      {
        "id": "code-21-py",
        "language": "py",
        "characters": 9337
      },
      {
        "id": "code-22-py",
        "language": "py",
        "characters": 6193
      },
      {
        "id": "code-23-py",
        "language": "py",
        "characters": 6124
      },
      {
        "id": "code-24-py",
        "language": "py",
        "characters": 10282
      },
      {
        "id": "code-25-py",
        "language": "py",
        "characters": 8145
      },
      {
        "id": "code-26-py",
        "language": "py",
        "characters": 7960
      },
      {
        "id": "code-27-py",
        "language": "py",
        "characters": 6492
      },
      {
        "id": "code-28-py",
        "language": "py",
        "characters": 6511
      },
      {
        "id": "code-29-py",
        "language": "py",
        "characters": 7143
      },
      {
        "id": "code-30-py",
        "language": "py",
        "characters": 6247
      },
      {
        "id": "code-31-py",
        "language": "py",
        "characters": 7043
      },
      {
        "id": "code-32-py",
        "language": "py",
        "characters": 7348
      },
      {
        "id": "code-33-py",
        "language": "py",
        "characters": 6886
      },
      {
        "id": "code-34-py",
        "language": "py",
        "characters": 7554
      },
      {
        "id": "code-35-py",
        "language": "py",
        "characters": 6966
      },
      {
        "id": "code-36-py",
        "language": "py",
        "characters": 5243
      },
      {
        "id": "code-37-py",
        "language": "py",
        "characters": 5594
      },
      {
        "id": "code-38-py",
        "language": "py",
        "characters": 7606
      },
      {
        "id": "code-39-ts",
        "language": "ts",
        "characters": 7885
      },
      {
        "id": "code-40-ts",
        "language": "ts",
        "characters": 7988
      },
      {
        "id": "code-41-ts",
        "language": "ts",
        "characters": 6213
      },
      {
        "id": "code-42-ts",
        "language": "ts",
        "characters": 7362
      },
      {
        "id": "code-43-ts",
        "language": "ts",
        "characters": 7795
      },
      {
        "id": "code-44-ts",
        "language": "ts",
        "characters": 7658
      },
      {
        "id": "code-45-html",
        "language": "html",
        "characters": 7413
      },
      {
        "id": "code-46-html",
        "language": "html",
        "characters": 7603
      },
      {
        "id": "code-47-css",
        "language": "css",
        "characters": 5906
      },
      {
        "id": "code-48-css",
        "language": "css",
        "characters": 6427
      },
      {
        "id": "code-49-css",
        "language": "css",
        "characters": 6228
      },
      {
        "id": "code-50-css",
        "language": "css",
        "characters": 5611
      },
      {
        "id": "code-51-sql",
        "language": "sql",
        "characters": 6267
      },
      {
        "id": "code-52-sql",
        "language": "sql",
        "characters": 6200
      },
      {
        "id": "code-53-sql",
        "language": "sql",
        "characters": 4871
      },
      {
        "id": "code-54-sql",
        "language": "sql",
        "characters": 5624
      },
      {
        "id": "code-55-sh",
        "language": "sh",
        "characters": 5987
      },
      {
        "id": "code-56-sh",
        "language": "sh",
        "characters": 6675
      },
      {
        "id": "code-57-sh",
        "language": "sh",
        "characters": 6223
      },
      {
        "id": "code-58-sh",
        "language": "sh",
        "characters": 7212
      },
      {
        "id": "code-59-go",
        "language": "go",
        "characters": 9368
      },
      {
        "id": "code-60-go",
        "language": "go",
        "characters": 6940
      },
      {
        "id": "code-61-go",
        "language": "go",
        "characters": 8899
      },
      {
        "id": "code-62-rs",
        "language": "rs",
        "characters": 7914
      },
      {
        "id": "code-63-rs",
        "language": "rs",
        "characters": 6964
      },
      {
        "id": "code-64-rs",
        "language": "rs",
        "characters": 7408
      },
      {
        "id": "code-65-c",
        "language": "c",
        "characters": 8200
      },
      {
        "id": "code-66-c",
        "language": "c",
        "characters": 7339
      },
      {
        "id": "code-67-c",
        "language": "c",
        "characters": 7082
      },
      {
        "id": "code-68-java",
        "language": "java",
        "characters": 9369
      },
      {
        "id": "code-69-java",
        "language": "java",
        "characters": 7230
      },
      {
        "id": "code-70-java",
        "language": "java",
        "characters": 7788
      },
      {
        "id": "code-71-json",
        "language": "json",
        "characters": 5114
      },
      {
        "id": "code-72-yaml",
        "language": "yaml",
        "characters": 6153
      },
      {
        "id": "code-73-docker",
        "language": "docker",
        "characters": 5858
      },
      {
        "id": "code-74-md",
        "language": "md",
        "characters": 6837
      },
      {
        "id": "code-75-diff",
        "language": "diff",
        "characters": 6404
      }
    ]
  },
  "general": {
    "writers": 25,
    "characters": 175269,
    "parts": [
      {
        "id": "gen-01",
        "characters": 7020
      },
      {
        "id": "gen-02",
        "characters": 7818
      },
      {
        "id": "gen-03",
        "characters": 8071
      },
      {
        "id": "gen-04",
        "characters": 7452
      },
      {
        "id": "gen-05",
        "characters": 8558
      },
      {
        "id": "gen-06",
        "characters": 7788
      },
      {
        "id": "gen-07",
        "characters": 7185
      },
      {
        "id": "gen-08",
        "characters": 7275
      },
      {
        "id": "gen-09",
        "characters": 5977
      },
      {
        "id": "gen-10",
        "characters": 5042
      },
      {
        "id": "gen-11",
        "characters": 7751
      },
      {
        "id": "gen-12",
        "characters": 7895
      },
      {
        "id": "gen-13",
        "characters": 6599
      },
      {
        "id": "gen-14",
        "characters": 7704
      },
      {
        "id": "gen-15",
        "characters": 4470
      },
      {
        "id": "gen-16",
        "characters": 4291
      },
      {
        "id": "gen-17",
        "characters": 6726
      },
      {
        "id": "gen-18",
        "characters": 7974
      },
      {
        "id": "gen-19",
        "characters": 5431
      },
      {
        "id": "gen-20",
        "characters": 7903
      },
      {
        "id": "gen-21",
        "characters": 7876
      },
      {
        "id": "gen-22",
        "characters": 7169
      },
      {
        "id": "gen-23",
        "characters": 7048
      },
      {
        "id": "gen-24",
        "characters": 8079
      },
      {
        "id": "gen-25",
        "characters": 6119
      }
    ]
  }
};
