#!/usr/bin/env node
/*
 * fetch-fonts.mjs — rebuild app/styles/fonts.css.
 *
 * The design bundle calls for Archivo (display and body) and IBM Plex Mono
 * (the small upper-case labels). Neither draws Hebrew, so Rubik stays as the
 * Hebrew face and the browser falls back to it per glyph: Latin and digits
 * come out in Archivo, Hebrew in Rubik, on the same line.
 *
 * Everything is inlined as base64. The app declares
 * `font-src 'self' data:` and is meant to work with the network off, so a
 * @import of fonts.googleapis.com would simply render nothing.
 *
 * Usage: node app/tools/fetch-fonts.mjs [rubik.css]
 *   rubik.css — the existing Rubik @font-face rules to carry over. Defaults to
 *               the copy kept in this repo at app/styles/rubik.css.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'styles/fonts.css');
const RUBIK = process.argv[2] || resolve(ROOT, 'styles/rubik.css');

const CSS_URL = 'https://fonts.googleapis.com/css2'
  + '?family=Archivo:wght@400;500;600;700;800;900'
  + '&family=IBM+Plex+Mono:wght@400;500;600'
  + '&display=swap';

// A modern desktop UA is what makes Google serve woff2 rather than ttf.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

// Hebrew comes from Rubik, so only the Latin subset of the two new faces is
// worth carrying. Dropping the rest saves about 400 KB.
const KEEP = new Set(['latin']);

async function get(url, asBuffer) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
}

const css = await get(CSS_URL, false);

// Google's CSS emits a /* subset */ comment before each @font-face block.
const blocks = [...css.matchAll(/\/\*\s*([^*]+?)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g)];
if (!blocks.length) throw new Error('no @font-face blocks came back');

/* Archivo ships as a variable font: Google hands back the same file for every
 * weight asked for. Embedding it six times would cost 200 KB to say one thing,
 * so faces are collected per file and a shared file becomes one @font-face
 * carrying the whole weight range. */
const faces = new Map();   // woff2 url -> {family, weights:Set, range}
for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;
  const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block);
  if (!url) continue;
  const family = /font-family:\s*'([^']+)'/.exec(block)[1];
  const weight = +/font-weight:\s*(\d+)/.exec(block)[1];
  const range = /unicode-range:\s*([^;]+);/.exec(block);
  const seen = faces.get(url[1]);
  if (seen) { seen.weights.add(weight); continue; }
  faces.set(url[1], { family, weights: new Set([weight]), range: range && range[1].trim() });
}

const out = [];
let bytes = 0;
for (const [url, f] of faces) {
  const buf = await get(url, true);
  bytes += buf.length;
  const ws = [...f.weights].sort((a, b) => a - b);
  const weight = ws.length > 1 ? `${ws[0]} ${ws[ws.length - 1]}` : `${ws[0]}`;
  out.push(
    `@font-face{font-family:'${f.family}';font-style:normal;font-weight:${weight};` +
    `font-display:swap;src:url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2')` +
    (f.range ? `;unicode-range:${f.range}` : '') + '}'
  );
  console.log(`  ${f.family} ${weight} — ${(buf.length / 1024).toFixed(1)} KB`);
}

const rubik = readFileSync(RUBIK, 'utf8').trim();

writeFileSync(OUT,
  `/* fonts.css — GENERATED by app/tools/fetch-fonts.mjs. Do not edit by hand.
 *
 * Archivo and IBM Plex Mono (Latin only) from the design bundle, and Rubik
 * (Latin + Hebrew) carried over from the original single file. Archivo draws
 * no Hebrew, so Hebrew falls through to Rubik one glyph at a time — which is
 * the whole trick that lets a Hebrew interface wear a Latin design.
 *
 * All three are licensed under the SIL Open Font License 1.1.
 */

/* ===== Rubik — the Hebrew face ===== */
${rubik}

/* ===== Archivo — display and body, Latin ===== */
/* ===== IBM Plex Mono — the small upper-case labels, Latin ===== */
${out.join('\n')}
`);

console.log(`\n✓ ${OUT}\n  ${out.length} new faces, ${(bytes / 1024).toFixed(0)} KB of woff2 before base64`);
