/*
 * art.player.js — the plumber, drawn a pixel at a time.
 *
 * Every frame is a grid of slot letters, resolved through a palette at atlas
 * build time (see palettes.js). Three colours plus transparent, which is what
 * a hardware sprite got:
 *
 *   r  the red of the cap and shirt        (white when he has the flower)
 *   s  skin
 *   d  the dark brown doing the work of four things at once — hair, eyes,
 *      moustache, overalls, shoes. That sharing is not laziness, it is the
 *      original constraint, and copying it is most of why the silhouette
 *      reads correctly at 16 pixels.
 *   w  white, used only for the overall buttons on the big sprite
 *
 * Sprites are drawn facing right and mirrored at draw time, so there is one
 * of each pose rather than two that can drift apart.
 *
 * Small is 16x16, big is 16x32, and the big sprite's head is deliberately the
 * same head one row lower: growing has to read as the same character getting
 * taller, not as a swap to a different one.
 */

/* ------------------------------------------------------------------ *
 * Small
 * ------------------------------------------------------------------ */

const SMALL_HEAD = [
  '......rrrrr.....',
  '.....rrrrrrrrr..',
  '.....dddsssds...',
  '....ddsdsssdsss.',
  '....ddsddsssdsss',
  '....ddddssssdddd',
  '......ssssssss..',
];

export const PLAYER_ART = {
  small_idle: { w: 16, h: 16, pal: 'mario', rows: [
    ...SMALL_HEAD,
    '.....rrrdrrr....',
    '....rrrrdrrrr...',
    '...srrrrdddrrrs.',
    '...ssrrdddddrss.',
    '...ssdddddddss..',
    '.....ddddddd....',
    '.....dd..dd.....',
    '....ddd..ddd....',
    '...dddd..dddd...',
  ] },

  small_walk0: { w: 16, h: 16, pal: 'mario', rows: [
    ...SMALL_HEAD,
    '.....rrrrdrr....',
    '....srrrrdrrr...',
    '...ssrrrdddrr...',
    '...ssrrdddddr...',
    '.....dddddddss..',
    '....ddddddddss..',
    '...dddd..dd.....',
    '..dddd...ddd....',
    '..ddd.....ddd...',
  ] },

  small_walk1: { w: 16, h: 16, pal: 'mario', rows: [
    ...SMALL_HEAD,
    '.....rrrdrrrs...',
    '....rrrrdrrrss..',
    '...srrrdddrrss..',
    '...ssrdddddd....',
    '....sdddddddd...',
    '.....dddddddd...',
    '.....ddddddd....',
    '....dddd.ddd....',
    '...dddd...dd....',
  ] },

  small_walk2: { w: 16, h: 16, pal: 'mario', rows: [
    ...SMALL_HEAD,
    '....srrrdrrr....',
    '...ssrrrdrrrs...',
    '...ssrrdddrrss..',
    '....srdddddrs...',
    '.....ddddddd....',
    '....ddddddddd...',
    '...dddd..dddd...',
    '..dddd....ddd...',
    '..ddd......dd...',
  ] },

  small_jump: { w: 16, h: 16, pal: 'mario', rows: [
    ...SMALL_HEAD,
    '...s..rrdrr..s..',
    '..sss.rrdrr.sss.',
    '..sssrrrdrrrsss.',
    '...srrrrdrrrrs..',
    '....rrdddddrr...',
    '.....ddddddd....',
    '....ddd..ddd....',
    '...ddd....ddd...',
    '..dddd....dddd..',
  ] },

  small_skid: { w: 16, h: 16, pal: 'mario', rows: [
    '.....rrrrr......',
    '..rrrrrrrrrr....',
    '..dddsssdsss....',
    '..dsdsssdssss...',
    '..dsddsssdssss..',
    '..ddddssssdddd..',
    '....ssssssss....',
    '...srrrdrrr.....',
    '..ssrrrdrrrr....',
    '..ssrrrdddrrr...',
    '...srrdddddrr...',
    '....ddddddddd...',
    '.....dddddddd...',
    '....ddd...ddd...',
    '...dddd....dd...',
    '..ddddd.........',
  ] },

  small_dead: { w: 16, h: 16, pal: 'mario', rows: [
    '......rrrrr.....',
    '.....rrrrrrrrr..',
    '.....rrrrrrrrr..',
    '....ssssssssss..',
    '....sdssssdsss..',
    '....sssssssss...',
    '....dddddddd....',
    '.....ssssss.....',
    'ss...rrrdrrr..ss',
    '.ss.rrrrdrrrr.s.',
    '..ssrrrdddrrrss.',
    '...srrdddddrrs..',
    '....ddddddddd...',
    '.....ddd.ddd....',
    '....dddd.dddd...',
    '...dddd...dddd..',
  ] },

  small_swim0: { w: 16, h: 16, pal: 'mario', rows: [
    ...SMALL_HEAD,
    '..s..rrrdrrr....',
    '.ss.rrrrdrrrr...',
    '.ss.rrrdddrrrs..',
    '..s.rrdddddrss..',
    '....ddddddddd...',
    '...ddddddddd....',
    '..dddd...dddd...',
    '.dddd......dd...',
    '..dd............',
  ] },

  small_swim1: { w: 16, h: 16, pal: 'mario', rows: [
    ...SMALL_HEAD,
    '.....rrrdrrr..s.',
    '....rrrrdrrrr.ss',
    '...srrrdddrrrsss',
    '...ssrdddddrrs..',
    '....ddddddddd...',
    '.....ddddddd....',
    '....ddd...ddd...',
    '...ddd.....dd...',
    '..ddd...........',
  ] },

  small_climb: { w: 16, h: 16, pal: 'mario', rows: [
    '.....rrrrrr.....',
    '....rrrrrrrr....',
    '....dddsssdd....',
    '....ddssssdd....',
    '....ddssssdd....',
    '.....dddddd.....',
    '.....ssssss.....',
    '..s..rrrrr..s...',
    '.ss.rrrrrrr.ss..',
    '.ss.rrdddrr.ss..',
    '..s.rdddddr.s...',
    '....ddddddd.....',
    '....dddddddd....',
    '....dd...dd.....',
    '...ddd...ddd....',
    '..dddd...dddd...',
  ] },

  small_climb1: { w: 16, h: 16, pal: 'mario', rows: [
    '.....rrrrrr.....',
    '....rrrrrrrr....',
    '....ddsssddd....',
    '....ddssssdd....',
    '....ddssssdd....',
    '.....dddddd.....',
    '.....ssssss.....',
    '...s..rrrrr..s..',
    '..ss.rrrrrrr.ss.',
    '..ss.rrdddrr.ss.',
    '...s.rdddddr.s..',
    '.....ddddddd....',
    '....dddddddd....',
    '.....dd..dd.....',
    '....ddd..ddd....',
    '...dddd..dddd...',
  ] },
};

/* ------------------------------------------------------------------ *
 * Big. Same face, one row further down, on a body twice as tall.
 * ------------------------------------------------------------------ */

const BIG_HEAD = [
  '.......rrrrr....',
  '......rrrrrrrrr.',
  '.....rrrrrrrrrrr',
  '.....dddsssdss..',
  '....ddsdsssdsss.',
  '....ddsddsssdsss',
  '....ddddssssddd.',
  '......ssssssss..',
  '.....dddddd.....',
];

export const PLAYER_BIG_ART = {
  big_idle: { w: 16, h: 32, pal: 'mario', rows: [
    ...BIG_HEAD,
    '.....rrrrrrr....',
    '....rrrrdrrrrr..',
    '...rrrrrdrrrrrr.',
    '..srrrrrdrrrrrs.',
    '..ssrrrdddrrrss.',
    '..ssrrdddddrrss.',
    '..ssrdddddddrss.',
    '..ssdddddddddss.',
    '...ddddddddddd..',
    '...dwddddddwd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...ddddd.ddddd..',
    '...dddd...dddd..',
    '...dddd...dddd..',
    '...dddd...dddd..',
    '...dddd...dddd..',
    '..ddddd..ddddd..',
    '..ddddd..ddddd..',
    '.dddddd..dddddd.',
    '.dddddd..dddddd.',
    '..ddddd..ddddd..',
  ] },

  big_walk0: { w: 16, h: 32, pal: 'mario', rows: [
    ...BIG_HEAD,
    '......rrrrrrr...',
    '.....rrrrdrrrr..',
    '....rrrrrdrrrrr.',
    '...srrrrrdrrrrs.',
    '...ssrrrdddrrss.',
    '...ssrrdddddrss.',
    '...ssrdddddddss.',
    '...ssddddddddd..',
    '....ddddddddd...',
    '....dwddddwd....',
    '....dddddddd....',
    '...ddddddddd....',
    '..dddddddddd....',
    '..dddd..dddd....',
    '.dddd...dddd....',
    '.dddd....dddd...',
    '.ddd.....dddd...',
    '.ddd......ddd...',
    'dddd......ddd...',
    'ddd.......dddd..',
    'ddd.......dddd..',
    '..........ddd...',
    '.........ddddd..',
  ] },

  big_walk1: { w: 16, h: 32, pal: 'mario', rows: [
    ...BIG_HEAD,
    '.....rrrrrrrr...',
    '....rrrrdrrrrr..',
    '...rrrrrdrrrrrr.',
    '...rrrrrdrrrrrrs',
    '..srrrrdddrrrrss',
    '..ssrrdddddrrrss',
    '..ssrddddddddrs.',
    '..ssdddddddddd..',
    '...ddddddddddd..',
    '...dwddddddwd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '....dddddddd....',
    '....ddd.dddd....',
    '...dddd..ddd....',
    '..dddd...dddd...',
    '..ddd.....ddd...',
    '.dddd.....dddd..',
    '.ddd.......ddd..',
    'dddd.......dddd.',
    'ddd.........ddd.',
  ] },

  big_walk2: { w: 16, h: 32, pal: 'mario', rows: [
    ...BIG_HEAD,
    '....rrrrrrr.....',
    '...rrrrdrrrrr...',
    '..rrrrrdrrrrrr..',
    '..rrrrrdrrrrrrs.',
    '.srrrrdddrrrrss.',
    '.ssrrdddddrrrss.',
    '.ssrdddddddrrss.',
    '.ssddddddddddss.',
    '..ddddddddddd...',
    '..dwddddddwd....',
    '..dddddddddd....',
    '..dddddddddd....',
    '..dddddddddd....',
    '...ddddddddd....',
    '...dddd.dddd....',
    '...dddd..dddd...',
    '...ddd...dddd...',
    '...ddd....dddd..',
    '..dddd....dddd..',
    '..ddd......ddd..',
    '.dddd......dddd.',
    '.ddd........ddd.',
    'dddd........dddd',
  ] },

  big_jump: { w: 16, h: 32, pal: 'mario', rows: [
    ...BIG_HEAD,
    '...s..rrrrr..s..',
    '..sss.rrdrr.sss.',
    '..sssrrrdrrrsss.',
    '..sssrrrdrrrsss.',
    '...srrrdddrrrs..',
    '....rrdddddrr...',
    '....rdddddddr...',
    '....ddddddddd...',
    '...ddddddddddd..',
    '...dwddddddwd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...ddddd.ddddd..',
    '...dddd...dddd..',
    '..ddddd...dddd..',
    '..dddd.....ddd..',
    '.ddddd.....ddd..',
    '.dddd.......dd..',
    'ddddd.......dd..',
    'dddd............',
    '.dd.............',
  ] },

  big_skid: { w: 16, h: 32, pal: 'mario', rows: [
    '.....rrrrr......',
    '...rrrrrrrrrr...',
    '..rrrrrrrrrrrr..',
    '..dddsssdsss....',
    '..dsdsssdssss...',
    '..dsddsssdssss..',
    '..ddddssssdddd..',
    '....ssssssss....',
    '.....dddddd.....',
    '...srrrrrrr.....',
    '..ssrrrdrrrrr...',
    '..ssrrrdrrrrrr..',
    '..ssrrrdrrrrrrs.',
    '...srrrdddrrrss.',
    '....rrdddddrrss.',
    '....rdddddddrs..',
    '....ddddddddd...',
    '...ddddddddddd..',
    '...dwddddddwd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...ddddd.ddddd..',
    '...dddd...dddd..',
    '..ddddd...dddd..',
    '..dddd....dddd..',
    '.ddddd.....ddd..',
    '.dddd......dddd.',
    'ddddd......dddd.',
    'dddd........ddd.',
    '.ddd............',
    '..d.............',
  ] },

  big_crouch: { w: 16, h: 32, pal: 'mario', rows: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '.......rrrrr....',
    '......rrrrrrrrr.',
    '.....rrrrrrrrrrr',
    '.....dddsssdss..',
    '....ddsdsssdsss.',
    '....ddsddsssdsss',
    '....ddddssssddd.',
    '......ssssssss..',
    '..s..rrrrrrr..s.',
    '.ss.rrrdrrrrr.ss',
    '.ss.rrdddrrrr.ss',
    '..s.rdddddddr.s.',
    '....ddddddddd...',
    '...dwddddddwd...',
    '...dddddddddd...',
    '..ddddd..ddddd..',
    '.dddddd..dddddd.',
  ] },

  big_swim0: { w: 16, h: 32, pal: 'mario', rows: [
    ...BIG_HEAD,
    '..s...rrrrrr....',
    '.ss..rrrdrrrrr..',
    '.ss.rrrrdrrrrrr.',
    '..s.rrrrdrrrrrs.',
    '....rrrdddrrrss.',
    '....rrdddddrrss.',
    '....rdddddddrss.',
    '....ddddddddddd.',
    '...ddddddddddd..',
    '...dwddddddwd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...ddddddddddd..',
    '...dddd..ddddd..',
    '..dddd....dddd..',
    '..ddd.....dddd..',
    '.dddd......ddd..',
    '.ddd.......dddd.',
    'dddd........ddd.',
    'ddd.........dddd',
    '.............dd.',
  ] },

  big_swim1: { w: 16, h: 32, pal: 'mario', rows: [
    ...BIG_HEAD,
    '.....rrrrrrr..s.',
    '....rrrrdrrrr.ss',
    '...rrrrrdrrrrsss',
    '..srrrrrdrrrrss.',
    '..ssrrrdddrrrs..',
    '..ssrrdddddrr...',
    '..ssrdddddddr...',
    '..ssdddddddddd..',
    '...ddddddddddd..',
    '...dwddddddwd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...dddddddddd...',
    '...ddddd.ddddd..',
    '...dddd...dddd..',
    '...dddd...dddd..',
    '..ddddd...dddd..',
    '..dddd.....ddd..',
    '.ddddd.....dddd.',
    '.dddd.......ddd.',
    'ddddd.......dddd',
    '.ddd............',
  ] },

  big_climb: { w: 16, h: 32, pal: 'mario', rows: [
    '......rrrrrr....',
    '.....rrrrrrrr...',
    '.....dddsssdd...',
    '.....ddssssdd...',
    '.....ddssssdd...',
    '......dddddd....',
    '......ssssss....',
    '......dddddd....',
    '..s...rrrrrr..s.',
    '.ss..rrrrrrrr.ss',
    '.ss..rrrdddrr.ss',
    '..s..rrdddddr.s.',
    '.....rdddddddr..',
    '.....ddddddddd..',
    '.....dwddddwd...',
    '.....dddddddd...',
    '.....dddddddd...',
    '.....dddddddd...',
    '.....dddddddd...',
    '.....ddd.dddd...',
    '.....ddd..ddd...',
    '....dddd..ddd...',
    '....ddd...dddd..',
    '....ddd...dddd..',
    '....ddd....ddd..',
    '...dddd....ddd..',
    '...dddd....dddd.',
    '...ddd.....dddd.',
    '..ddddd...ddddd.',
    '..ddddd...ddddd.',
    '.dddddd...dddddd',
    '..dddd.....dddd.',
  ] },

  big_climb1: { w: 16, h: 32, pal: 'mario', rows: [
    '......rrrrrr....',
    '.....rrrrrrrr...',
    '.....ddsssddd...',
    '.....ddssssdd...',
    '.....ddssssdd...',
    '......dddddd....',
    '......ssssss....',
    '......dddddd....',
    '...s..rrrrrr..s.',
    '..ss.rrrrrrrr.ss',
    '..ss.rrrdddrr.ss',
    '...s.rrdddddr.s.',
    '.....rdddddddr..',
    '.....ddddddddd..',
    '.....dwddddwd...',
    '.....dddddddd...',
    '.....dddddddd...',
    '.....dddddddd...',
    '.....dddddddd...',
    '.....dddd.ddd...',
    '.....dddd.ddd...',
    '.....dddd.ddd...',
    '.....dddd.ddd...',
    '....ddddd.dddd..',
    '....dddd..dddd..',
    '....dddd..dddd..',
    '....dddd..dddd..',
    '...ddddd..ddddd.',
    '...ddddd..ddddd.',
    '..dddddd..dddddd',
    '..dddddd..dddddd',
    '...ddddd..ddddd.',
  ] },
};

/* The frame the transform animation flickers through: a body somewhere
   between the two, so growing and shrinking are visibly the same event
   running in opposite directions. */
PLAYER_BIG_ART.big_grow = { w: 16, h: 32, pal: 'mario', rows: [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '.......rrrrr....',
  '......rrrrrrrrr.',
  '.....rrrrrrrrrrr',
  '.....dddsssdss..',
  '....ddsdsssdsss.',
  '....ddsddsssdsss',
  '....ddddssssddd.',
  '......ssssssss..',
  '.....dddddd.....',
  '.....rrrrrrr....',
  '....rrrrdrrrrr..',
  '...rrrrrdrrrrrr.',
  '..srrrrrdrrrrrs.',
  '..ssrrrdddrrrss.',
  '..ssrrdddddrrss.',
  '..ssdddddddddss.',
  '...ddddddddddd..',
  '...dwddddddwd...',
  '...dddddddddd...',
  '...dddddddddd...',
  '...ddddd.ddddd..',
  '...dddd...dddd..',
  '..ddddd..ddddd..',
  '.dddddd..dddddd.',
  '..ddddd..ddddd..',
] };

export const ALL_PLAYER_ART = { ...PLAYER_ART, ...PLAYER_BIG_ART };
