/*
 * art.enemies.js — everything that wants you dead.
 *
 * Slot letters, resolved by the palettes in palettes.js:
 *   r  body / shell        s  belly, skin, soles
 *   d  outline             w  eye white and shell rings
 *   y  limbs and trim
 *
 * The colour split is deliberate: a Goomba and a "blue Goomba" are the same
 * pixels with a different palette, which is exactly how the underground got
 * its own bestiary in 1985 without a byte of new art. Anything that walks is
 * drawn facing right and flipped when it turns.
 */

export const ENEMY_ART = {
  /* ---------------- Goomba: two frames, feet swapping ---------------- */
  goomba0: { w: 16, h: 16, pal: 'goomba', rows: [
    '................',
    '.....rrrrrr.....',
    '...rrrrrrrrrr...',
    '..rrrrrrrrrrrr..',
    '..rrssrrrrssrr..',
    '..rsddsrrsddsr..',
    '..rsddsrrsddsr..',
    '..rrssrrrrssrr..',
    '..rrrrrrrrrrrr..',
    '..rrrrrrrrrrrr..',
    '..drrrrrrrrrrd..',
    '.dddrrrrrrrrddd.',
    '.ddddddddddddddd',
    'ssssdddddddssss.',
    'sssss.....sssss.',
    '................',
  ] },

  goomba1: { w: 16, h: 16, pal: 'goomba', rows: [
    '................',
    '.....rrrrrr.....',
    '...rrrrrrrrrr...',
    '..rrrrrrrrrrrr..',
    '..rrssrrrrssrr..',
    '..rsddsrrsddsr..',
    '..rsddsrrsddsr..',
    '..rrssrrrrssrr..',
    '..rrrrrrrrrrrr..',
    '..rrrrrrrrrrrr..',
    '..drrrrrrrrrrd..',
    '.dddrrrrrrrrddd.',
    'ddddddddddddddd.',
    '.ssssdddddddssss',
    '.sssss.....sssss',
    '................',
  ] },

  goomba_flat: { w: 16, h: 16, pal: 'goomba', rows: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..rrrrrrrrrrrr..',
    '.rrssrrrrrrssrr.',
    '.rsddsrrrrsddsr.',
    'ddddddddddddddddd'.slice(0, 16),
    'ssssddddddddssss',
  ] },

  /* ---------------- Koopa Troopa, 16x24 ---------------- */
  koopa0: { w: 16, h: 24, pal: 'koopa', rows: [
    '......dddd......',
    '.....dyyyyd.....',
    '....dyyyyyyd....',
    '....dywwyyyd....',
    '....dywdwyyd....',
    '....dyywyyydd...',
    '.....dyyyyyyd...',
    '......dyyyyd....',
    '.....ddyydd.....',
    '...ddrrrrrrdd...',
    '..drrwwrrwwrrd..',
    '.drrwwrrrrwwrrd.',
    '.drwwrrrrrrwwrd.',
    '.drwrrrrrrrrwrd.',
    '.drwrrrrrrrrwrd.',
    '.drwwrrrrrrwwrd.',
    '.drrwwrrrrwwrrd.',
    '..drrwwrrwwrrd..',
    '...ddrrrrrrdd...',
    '....dddddddd....',
    '....dyyyyyyd....',
    '...dyyd..dyyd...',
    '..dyyyd..dyyyd..',
    '..ddddd..ddddd..',
  ] },

  koopa1: { w: 16, h: 24, pal: 'koopa', rows: [
    '......dddd......',
    '.....dyyyyd.....',
    '....dyyyyyyd....',
    '....dywwyyyd....',
    '....dywdwyyd....',
    '....dyywyyydd...',
    '.....dyyyyyyd...',
    '......dyyyyd....',
    '.....ddyydd.....',
    '...ddrrrrrrdd...',
    '..drrwwrrwwrrd..',
    '.drrwwrrrrwwrrd.',
    '.drwwrrrrrrwwrd.',
    '.drwrrrrrrrrwrd.',
    '.drwrrrrrrrrwrd.',
    '.drwwrrrrrrwwrd.',
    '.drrwwrrrrwwrrd.',
    '..drrwwrrwwrrd..',
    '...ddrrrrrrdd...',
    '....dddddddd....',
    '....dyyyyyyd....',
    '....dyyyyyyd....',
    '...dyyyddyyyd...',
    '...ddddddddddd..',
  ] },

  /* Wings, drawn as their own sprite and stuck on the side of whatever is
     flying, so one pair serves the Koopa, the Buzzy and the flying platform
     enemies. */
  wing0: { w: 16, h: 16, pal: 'koopa', rows: [
    '................',
    '.....dddd.......',
    '...ddwwwwd......',
    '..dwwwwwwwd.....',
    '.dwwwwwwwwwd....',
    '.dwwwwwwwwwd....',
    '..dwwwwwwwd.....',
    '...ddwwwwd......',
    '.....dddd.......',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ] },

  wing1: { w: 16, h: 16, pal: 'koopa', rows: [
    '................',
    '................',
    '................',
    '.....dd.........',
    '....dwwd........',
    '...dwwwwd.......',
    '..dwwwwwwd......',
    '..dwwwwwwd......',
    '..dwwwwwwd......',
    '...dwwwwd.......',
    '....dwwd........',
    '.....dd.........',
    '................',
    '................',
    '................',
    '................',
  ] },

  shell: { w: 16, h: 16, pal: 'koopa', rows: [
    '................',
    '................',
    '.....dddddd.....',
    '...ddrrrrrrdd...',
    '..drrwwrrwwrrd..',
    '.drrwwrrrrwwrrd.',
    '.drwwrrrrrrwwrd.',
    '.drwrrrrrrrrwrd.',
    '.drwrrrrrrrrwrd.',
    '.drwwrrrrrrwwrd.',
    '.drrwwrrrrwwrrd.',
    '..drrwwrrwwrrd..',
    '...ddrrrrrrdd...',
    '....dddddddd....',
    '..yyyyyyyyyyyy..',
    '..dddddddddddd..',
  ] },

  shell_wake: { w: 16, h: 16, pal: 'koopa', rows: [
    '................',
    '................',
    '.....dddddd.....',
    '...ddrrrrrrdd...',
    '..drryyyyyyrrd..',
    '.drryyrrrryyrrd.',
    '.dryyrrrrrryyrd.',
    '.dryrrrrrrrryrd.',
    '.dyyrrwwwwrryyd.',
    '.drwwrrrrrrwwrd.',
    '.drrwwrrrrwwrrd.',
    '..drrwwrrwwrrd..',
    '...ddrrrrrrdd...',
    '....dddddddd....',
    '..yyyyyyyyyyyy..',
    '..dddddddddddd..',
  ] },

  /* ---------------- Piranha Plant, 16x24 ---------------- */
  piranha0: { w: 16, h: 24, pal: 'piranha', rows: [
    '....dddddddd....',
    '...dwwwwwwwwd...',
    '..dwwwwwwwwwwd..',
    '..dwwsssssswwd..',
    '.dwwsssssssswwd.',
    '.dwsssddddssswd.',
    '.dwssddddddsswd.',
    '.dwsdddddddddwd.',
    '.dddddddddddddd.',
    '..dwsdddddddwd..',
    '..dwwsssssswwd..',
    '...dwwwwwwwwd...',
    '....dddddddd....',
    '.....drrrrd.....',
    '.....drrrrd.....',
    '....dryyyyrd....',
    '....drrrrrrd....',
    '.....drrrrd.....',
    '.....dryyrd.....',
    '.....drrrrd.....',
    '....dryyyyrd....',
    '....drrrrrrd....',
    '.....drrrrd.....',
    '.....drrrrd.....',
  ] },

  piranha1: { w: 16, h: 24, pal: 'piranha', rows: [
    '....dddddddd....',
    '...dwwwwwwwwd...',
    '..dwwwwwwwwwwd..',
    '..dwwwwwwwwwwd..',
    '.dwwwwwwwwwwwwd.',
    '.dwwsssssssswwd.',
    '.dwsssssssssswd.',
    '.dwssssssssssdd.',
    '.dddddddddddddd.',
    '..dwssssssssdd..',
    '..dwwsssssswwd..',
    '...dwwwwwwwwd...',
    '....dddddddd....',
    '.....drrrrd.....',
    '.....drrrrd.....',
    '....dryyyyrd....',
    '....drrrrrrd....',
    '.....drrrrd.....',
    '.....dryyrd.....',
    '.....drrrrd.....',
    '....dryyyyrd....',
    '....drrrrrrd....',
    '.....drrrrd.....',
    '.....drrrrd.....',
  ] },

  /* ---------------- Fish and squid ---------------- */
  cheep0: { w: 16, h: 16, pal: 'cheep', rows: [
    '................',
    '.....dddddd.....',
    '...ddrrrrrrdd...',
    '..drrrrrrrrrrd..',
    '.drrrrrrrrrwwrd.',
    'drrrrrrrrrrwdwrd',
    'drssrrrrrrrwwwrd',
    'yddrssrrrrrrrrrd',
    'yddrssrrrrrrrrrd',
    'drssrrrrrrrrrrrd',
    '.drrrrrrrrrrrrd.',
    '..ddrrrrrrrrdd..',
    '...yddrrrrdd....',
    '..yyyddddd......',
    '..yyy...........',
    '................',
  ] },

  cheep1: { w: 16, h: 16, pal: 'cheep', rows: [
    '................',
    '.....dddddd.....',
    '...ddrrrrrrdd...',
    '..drrrrrrrrrrd..',
    '.drrrrrrrrrwwrd.',
    'drrrrrrrrrrwdwrd',
    'drssrrrrrrrwwwrd',
    'dddrssrrrrrrrrrd',
    'dddrssrrrrrrrrrd',
    'drssrrrrrrrrrrrd',
    '.drrrrrrrrrrrrd.',
    '..ddrrrrrrrrdd..',
    '..yddrrrrrdd....',
    '..yyyyddddd.....',
    '...yyy..........',
    '................',
  ] },

  blooper: { w: 16, h: 24, pal: 'blooper', rows: [
    '.....dddddd.....',
    '...ddrrrrrrdd...',
    '..drrrrrrrrrrd..',
    '.drrrrrrrrrrrrd.',
    '.drrrrrrrrrrrrd.',
    'drrrrrrrrrrrrrrd',
    'drrrddrrrrddrrrd',
    'drrrddrrrrddrrrd',
    'drrrrrrrrrrrrrrd',
    'drrrrrrrrrrrrrrd',
    '.drrrrrrrrrrrrd.',
    '..drrrrrrrrrrd..',
    '..dyddyddyddyd..',
    '..dyddyddyddyd..',
    '..dyddyddyddyd..',
    '..dyd.ydyd.dyd..',
    '..dyd.ydyd.dyd..',
    '..dy..ydyd..yd..',
    '...d..ydyd..d...',
    '......ydyd......',
    '......ydyd......',
    '......ydyd......',
    '.......dd.......',
    '................',
  ] },

  /* ---------------- Hammer Brother ---------------- */
  hammerbro0: { w: 16, h: 24, pal: 'hammerbro', rows: [
    '...dddddddddd...',
    '..dyyyyyyyyyyd..',
    '..dddddddddddd..',
    '...dyyyyyyyyd...',
    '...dywwyywwyd...',
    '...dywdwwdwyd...',
    '...dyyyyyyyyd...',
    '....dyyyyyyd....',
    '.....ddyydd.....',
    '...ddrrrrrrdd...',
    '..drrwwrrwwrrd..',
    '.drrwwrrrrwwrrd.',
    'ydrwwrrrrrrwwrdy',
    'ydrwrrrrrrrrwrdy',
    'ydrwrrrrrrrrwrdy',
    '.drwwrrrrrrwwrd.',
    '.drrwwrrrrwwrrd.',
    '..drrwwrrwwrrd..',
    '...ddrrrrrrdd...',
    '....dddddddd....',
    '....dyyyyyyd....',
    '...dyyd..dyyd...',
    '..dyyyd..dyyyd..',
    '..ddddd..ddddd..',
  ] },

  hammerbro1: { w: 16, h: 24, pal: 'hammerbro', rows: [
    '...dddddddddd...',
    '..dyyyyyyyyyyd..',
    '..dddddddddddd..',
    '...dyyyyyyyyd...',
    '...dywwyywwyd...',
    '...dywdwwdwyd...',
    '...dyyyyyyyyd...',
    '....dyyyyyyd....',
    '.....ddyydd.....',
    '.y.ddrrrrrrdd.y.',
    'yyydrrwwrrwwrryy',
    '.y.rrwwrrrrwwrd.',
    '..drwwrrrrrrwwd.',
    '..drwrrrrrrrrwd.',
    '..drwrrrrrrrrwd.',
    '..drwwrrrrrrwwd.',
    '..drrwwrrrrwwrd.',
    '...drrwwrrwwrd..',
    '...ddrrrrrrdd...',
    '....dddddddd....',
    '....dyyyyyyd....',
    '....dyyyyyyd....',
    '...dyyyddyyyd...',
    '...ddddddddddd..',
  ] },

  hammer: { w: 16, h: 16, pal: 'hammer', rows: [
    '................',
    '................',
    '....dddddd......',
    '...drrrrrrd.....',
    '...drrrrrrd.....',
    '...drrrrrrd.....',
    '...drrrrrrd.....',
    '....dddddd......',
    '......dsd.......',
    '......dsd.......',
    '......dsd.......',
    '......dsd.......',
    '......dsd.......',
    '......ddd.......',
    '................',
    '................',
  ] },

  /* ---------------- Lakitu and his Spiny ---------------- */
  lakitu: { w: 16, h: 24, pal: 'lakitu', rows: [
    '.....dddddd.....',
    '...ddrrrrrrdd...',
    '..drrwwrrwwrrd..',
    '.drrwwrrrrwwrrd.',
    '.drwwrrrrrrwwrd.',
    '.drwrrrrrrrrwrd.',
    '..ddrrrrrrrrdd..',
    '...dyyyyyyyyd...',
    '...dywwyywwyd...',
    '...dywdwwdwyd...',
    '...dyyyyyyyyd...',
    '....dyyyyyyd....',
    '.....dddddd.....',
    '..ddyyddddyydd..',
    '.dyyyyyyyyyyyyd.',
    'dyyyyyyyyyyyyyyd',
    'dyyyyyyyyyyyyyyd',
    'dyyyyyyyyyyyyyyd',
    '.dyyyyyyyyyyyyd.',
    '..ddyyyyyyyydd..',
    '....dddddddd....',
    '................',
    '................',
    '................',
  ] },

  spiny: { w: 16, h: 16, pal: 'spiny', rows: [
    '................',
    '..d..d....d..d..',
    '..dd.dd..dd.dd..',
    '...ddyddddyydd..',
    '..dyyyyyyyyyyd..',
    '.dyyyyyyyyyyyyd.',
    '.dyyyyyyyyyyyyd.',
    '..dyyyyyyyyyyd..',
    '...ddddddddddd..',
    '..drrwwrrwwrrd..',
    '..drwdwrrwdwrd..',
    '..drrwwrrwwrrd..',
    '..drrrrrrrrrrd..',
    '...dddddddddd...',
    '..ss........ss..',
    '..sss......sss..',
  ] },

  spiny_egg: { w: 16, h: 16, pal: 'spiny', rows: [
    '................',
    '................',
    '..d..d....d..d..',
    '..dd.dd..dd.dd..',
    '...ddyddddydd...',
    '..dyyyyyyyyyyd..',
    '.dyyyyyyyyyyyyd.',
    '.dyyyyyyyyyyyyd.',
    '.dyyyyyyyyyyyyd.',
    '.dyyyyyyyyyyyyd.',
    '..dyyyyyyyyyyd..',
    '...ddyddddydd...',
    '..dd.dd..dd.dd..',
    '..d..d....d..d..',
    '................',
    '................',
  ] },

  /* ---------------- Artillery ---------------- */
  bullet: { w: 16, h: 16, pal: 'bullet', rows: [
    '................',
    '....dddddddd....',
    '..dddrrrrrrddd..',
    '.ddrrrrrrrrrrdd.',
    'ddrrrrrrrrrrrrdd',
    'drrsssrrrrrrrrrd',
    'drsdddsrrrrrrrrd',
    'drsdddsrrrrrrrrd',
    'drsdddsrrrrrrrrd',
    'drrsssrrrrrrrrrd',
    'ddrrrrrrrrrrrrdd',
    '.ddrrrrrrrrrrdd.',
    '..dddrrrrrrddd..',
    '....dddddddd....',
    '................',
    '................',
  ] },

  cannon_top: { w: 16, h: 16, pal: 'bullet', rows: [
    'dddddddddddddddd',
    'dssssssssssssssd',
    'ds............sd',
    'ds..........dssd',
    'ds........ddssdd',
    'ds.......dsssddd',
    'ds......dssssddd',
    'ds......dssssddd',
    'ds......dssssddd',
    'ds......dssssddd',
    'ds.......dsssddd',
    'ds........ddssdd',
    'ds..........dssd',
    'ds............sd',
    'dssssssssssssssd',
    'dddddddddddddddd',
  ] },

  cannon_base: { w: 16, h: 16, pal: 'bullet', rows: [
    'dddddddddddddddd',
    'dssssssssssssssd',
    'ds.ssssssssss.sd',
    'ds.s........s.sd',
    'ds.s.ssssss.s.sd',
    'ds.s.s....s.s.sd',
    'ds.s.s....s.s.sd',
    'ds.s.s....s.s.sd',
    'ds.s.s....s.s.sd',
    'ds.s.s....s.s.sd',
    'ds.s.s....s.s.sd',
    'ds.s.ssssss.s.sd',
    'ds.s........s.sd',
    'ds.ssssssssss.sd',
    'dssssssssssssssd',
    'dddddddddddddddd',
  ] },

  podoboo: { w: 16, h: 16, pal: 'podoboo', rows: [
    '................',
    '.......ss.......',
    '......ssss......',
    '.....ssssss.....',
    '....ssswwsss....',
    '...ssswwwwsss...',
    '...sswwwwwwss...',
    '..rsswwwwwwssr..',
    '..rrswwwwwwsrr..',
    '..rrrswwwwsrrr..',
    '...rrrsswwsrrr..',
    '...rrrrssssrrr..',
    '....rrrrrrrrr...',
    '.....rrrrrrr....',
    '......rrrrr.....',
    '.......rrr......',
  ] },

  /* ---------------- The one at the end of every castle ----------------
     32x32, twice the size of anything else on screen, which is the whole
     point of him. */
  boss0: { w: 32, h: 32, pal: 'boss', rows: [
    '...........dddddddd.............',
    '.........ddyyyyyyyydd...........',
    '........dyyyyyyyyyyyyd..........',
    '.......dyyddyyyyyyddyyd.........',
    '......dyyddddyyyyddddyyd........',
    '......dyddwwdyyyydwwddyd........',
    '.....dyyddwwdyyyydwwddyyd.......',
    '.....dyyyddddyyyyddddyyyd.......',
    '....ddyyyyyyyyyyyyyyyyyydd......',
    '...dwwwwwwwwwwwwwwwwwwwwwwd.....',
    '...dwddwddwddwddwddwddwddwd.....',
    '....dwwwwwwwwwwwwwwwwwwwwd......',
    '.....dyyyyyyyyyyyyyyyyyyd.......',
    '..dddyyyyyyyyyyyyyyyyyyyddd.....',
    '.ddrrddyyyyyyyyyyyyyyddrrdd.....',
    'ddrrrrddyyyyyyyyyyyyddrrrrdd....',
    'drrwwrrddyyyyyyyyyyddrrwwrrd....',
    'drwwwwrrdyyyyyyyyyydrrwwwwrd....',
    'drrwwrrrdyywwwwwwyydrrrwwrrd....',
    '.ddrrrddyywwwwwwwwyyddrrrdd.....',
    '..ddddd.ywwwwwwwwwwy.ddddd......',
    '........ywwwwwwwwwwy............',
    '.......dywwwwwwwwwwyd...........',
    '......ddyywwwwwwwwyydd..........',
    '.....dyyyyywwwwwwyyyyyd.........',
    '....dyyyyyyyyyyyyyyyyyyd........',
    '....dyyyyyyyyyyyyyyyyyyd........',
    '....ddyyyyyyyyyyyyyyyydd........',
    '.....ddyyyddddddddyyydd.........',
    '...dddyyyddd....dddyyyddd.......',
    '..dsssssssd......dsssssssd......',
    '..dddddddd........dddddddd......',
  ] },

  boss1: { w: 32, h: 32, pal: 'boss', rows: [
    '...........dddddddd.............',
    '.........ddyyyyyyyydd...........',
    '........dyyyyyyyyyyyyd..........',
    '.......dyyddyyyyyyddyyd.........',
    '......dyyddddyyyyddddyyd........',
    '......dyddwwdyyyydwwddyd........',
    '.....dyyddwwdyyyydwwddyyd.......',
    '.....dyyyddddyyyyddddyyyd.......',
    '....ddyyyyyyyyyyyyyyyyyydd......',
    '...dwwwwwwwwwwwwwwwwwwwwwwd.....',
    '...dwddwddwddwddwddwddwddwd.....',
    '....dwwwwwwwwwwwwwwwwwwwwd......',
    '.....dyyyyyyyyyyyyyyyyyyd.......',
    '..dddyyyyyyyyyyyyyyyyyyyddd.....',
    '.ddrrddyyyyyyyyyyyyyyddrrdd.....',
    'ddrrrrddyyyyyyyyyyyyddrrrrdd....',
    'drrwwrrddyyyyyyyyyyddrrwwrrd....',
    'drwwwwrrdyyyyyyyyyydrrwwwwrd....',
    'drrwwrrrdyywwwwwwyydrrrwwrrd....',
    '.ddrrrddyywwwwwwwwyyddrrrdd.....',
    '..ddddd.ywwwwwwwwwwy.ddddd......',
    '........ywwwwwwwwwwy............',
    '.......dywwwwwwwwwwyd...........',
    '......ddyywwwwwwwwyydd..........',
    '.....dyyyyywwwwwwyyyyyd.........',
    '....dyyyyyyyyyyyyyyyyyyd........',
    '....dyyyyyyyyyyyyyyyyyyd........',
    '....ddyyyyyyyyyyyyyyyydd........',
    '......ddyyyddddddyyydd..........',
    '.....dddyyydd..ddyyyddd.........',
    '....dsssssssd..dsssssssd........',
    '....dddddddd....dddddddd........',
  ] },

  boss_fire: { w: 16, h: 8, pal: 'podoboo', rows: [
    '................',
    '....rrrr...rr...',
    '..rrssssrrrssrr.',
    '.rsswwwwsssswwsr',
    '.rsswwwwsssswwsr',
    '..rrssssrrrssrr.',
    '....rrrr...rr...',
    '................',
  ] },
};
