/*
 * art.items.js — the things you want to touch, and the things you leave behind.
 *
 * The flower and the star are single drawings played through a palette cycle
 * (see CYCLE in palettes.js) rather than four drawings each: on the real
 * machine the sparkle was a palette write per frame, and doing it the same way
 * keeps the shapes locked together while the colours run.
 */

export const ITEM_ART = {
  mushroom: { w: 16, h: 16, pal: 'mushroom', rows: [
    '................',
    '.....dddddd.....',
    '...ddwwwwwwdd...',
    '..dwwwrrrrwwwd..',
    '.dwwwrrrrrrwwwd.',
    '.dwwrrrrrrrrwwd.',
    'dwwrrrwwwwrrrwwd',
    'dwrrrwwwwwwrrrwd',
    'drrrwwwwwwwwrrrd',
    'drrrwwwwwwwwrrrd',
    'ddrrrwwwwwwrrrdd',
    '.ddrrrrrrrrrrdd.',
    '..dssssssssssd..',
    '..dssddddddssd..',
    '..dssddddddssd..',
    '..dddddddddddd..',
  ] },

  flower: { w: 16, h: 16, pal: 'flower1', rows: [
    '................',
    '....dddddddd....',
    '...dwwrrrrwwd...',
    '..dwwrrrrrrwwd..',
    '..dwrrssssrrwd..',
    '..dwrsswwssrwd..',
    '..dwrsswwssrwd..',
    '..dwrrssssrrwd..',
    '..dwwrrrrrrwwd..',
    '...dwwrrrrwwd...',
    '....dddddddd....',
    '...ddd.dd.ddd...',
    '..dddd.dd.dddd..',
    '..dd...dd...dd..',
    '.......dd.......',
    '.......dd.......',
  ] },

  star_item: { w: 16, h: 16, pal: 'starItem1', rows: [
    '................',
    '.......dd.......',
    '......drrd......',
    '......drrd......',
    '.....drrrrd.....',
    'ddddddrssrdddddd',
    'drrrrrssssrrrrrd',
    '.drrrssddssrrrd.',
    '..drrssddssrrd..',
    '...drssddssrd...',
    '...drrssssrrd...',
    '..drrrssssrrrd..',
    '..drrrd..drrrd..',
    '.ddrrd....drrdd.',
    '.drrd......drrd.',
    '.dd..........dd.',
  ] },

  coin0: { w: 16, h: 16, pal: 'coin', rows: [
    '................',
    '......dddd......',
    '.....drrrrd.....',
    '....drrrrrrd....',
    '....drwwwwrd....',
    '....drwddwrd....',
    '....drwddwrd....',
    '....drwddwrd....',
    '....drwddwrd....',
    '....drwddwrd....',
    '....drwddwrd....',
    '....drwwwwrd....',
    '....drrrrrrd....',
    '.....drrrrd.....',
    '......dddd......',
    '................',
  ] },

  coin1: { w: 16, h: 16, pal: 'coin', rows: [
    '................',
    '.......dd.......',
    '......drrd......',
    '......drrd......',
    '.....drwwrd.....',
    '.....drwdrd.....',
    '.....drwdrd.....',
    '.....drwdrd.....',
    '.....drwdrd.....',
    '.....drwdrd.....',
    '.....drwdrd.....',
    '.....drwwrd.....',
    '......drrd......',
    '......drrd......',
    '.......dd.......',
    '................',
  ] },

  coin2: { w: 16, h: 16, pal: 'coin', rows: [
    '................',
    '.......dd.......',
    '.......dd.......',
    '.......dd.......',
    '......ddd.......',
    '......drd.......',
    '......drd.......',
    '......drd.......',
    '......drd.......',
    '......drd.......',
    '......drd.......',
    '......ddd.......',
    '.......dd.......',
    '.......dd.......',
    '.......dd.......',
    '................',
  ] },

  /* The coin that pops out of a block. Same shape, no outline — it is on
     screen for eight frames and reads as a flash of gold. */
  coin_pop: { w: 16, h: 16, pal: 'coin', rows: [
    '................',
    '......rrrr......',
    '.....rrrrrr.....',
    '....rrwwwwrr....',
    '....rrwddwrr....',
    '....rrwddwrr....',
    '....rrwddwrr....',
    '....rrwddwrr....',
    '....rrwddwrr....',
    '....rrwddwrr....',
    '....rrwddwrr....',
    '....rrwddwrr....',
    '....rrwwwwrr....',
    '.....rrrrrr.....',
    '......rrrr......',
    '................',
  ] },

  fireball0: { w: 8, h: 8, pal: 'fireball', rows: [
    '..dddd..',
    '.dsswwd.',
    'dswwwwsd',
    'dswwwwsd',
    'dsswwssd',
    'dssssssd',
    '.dssssd.',
    '..dddd..',
  ] },

  fireball1: { w: 8, h: 8, pal: 'fireball', rows: [
    '..dddd..',
    '.dwwssd.',
    'dwwwwssd',
    'dswwwwsd',
    'dsswwssd',
    'dssssssd',
    '.dssssd.',
    '..dddd..',
  ] },

  burst0: { w: 16, h: 16, pal: 'fireball', rows: [
    '................',
    '................',
    '.....d....d.....',
    '......dddd......',
    '.....dssssd.....',
    '....dsswwssd....',
    '..d.dswwwwsd.d..',
    '....dswwwwsd....',
    '....dsswwssd....',
    '.....dssssd.....',
    '......dddd......',
    '.....d....d.....',
    '................',
    '................',
    '................',
    '................',
  ] },

  burst1: { w: 16, h: 16, pal: 'fireball', rows: [
    '................',
    '...d........d...',
    '....d..dd..d....',
    '.....dd..dd.....',
    '....d.dddd.d....',
    '...d.dssssd.d...',
    '.d..dss..ssd..d.',
    '....ds....sd....',
    '....dss..ssd....',
    '...d.dssssd.d...',
    '....d.dddd.d....',
    '.....dd..dd.....',
    '....d..dd..d....',
    '...d........d...',
    '................',
    '................',
  ] },

  spring0: { w: 16, h: 32, pal: 'spring', rows: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..dddddddddddd..',
    '..dssssssssssd..',
    '..drrrrrrrrrrd..',
    '..dddddddddddd..',
    '....dssssssd....',
    '....drrrrrrd....',
    '....dddddddd....',
    '..dddddddddddd..',
    '..dssssssssssd..',
    '..drrrrrrrrrrd..',
    '..dddddddddddd..',
    '....dssssssd....',
    '....drrrrrrd....',
    '....dddddddd....',
    '..dddddddddddd..',
    '..dssssssssssd..',
    '..drrrrrrrrrrd..',
    '..dddddddddddd..',
    '....dssssssd....',
    '....drrrrrrd....',
    '....dddddddd....',
    '.dddddddddddddd.',
    '.drrrrrrrrrrrrd.',
    '.dddddddddddddd.',
  ] },

  spring1: { w: 16, h: 32, pal: 'spring', rows: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..dddddddddddd..',
    '..dssssssssssd..',
    '..drrrrrrrrrrd..',
    '..dddddddddddd..',
    '....dssssssd....',
    '....dddddddd....',
    '..dddddddddddd..',
    '..dssssssssssd..',
    '..drrrrrrrrrrd..',
    '..dddddddddddd..',
    '....dssssssd....',
    '....dddddddd....',
    '.dddddddddddddd.',
    '.drrrrrrrrrrrrd.',
    '.dddddddddddddd.',
    '................',
  ] },

  spring2: { w: 16, h: 32, pal: 'spring', rows: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..dddddddddddd..',
    '..dssssssssssd..',
    '..drrrrrrrrrrd..',
    '..dddddddddddd..',
    '....dssssssd....',
    '.dddddddddddddd.',
    '.drrrrrrrrrrrrd.',
    '.dddddddddddddd.',
    '................',
  ] },

  /* The axe on the castle bridge. Small, but it is the only thing on the
     screen that matters at that moment. */
  axe: { w: 16, h: 16, pal: 'axe', rows: [
    '................',
    '................',
    '....dddd........',
    '...drrrrd.......',
    '..drrrrrrd......',
    '..drrrrrrrd.....',
    '..drrrrrrsd.....',
    '..drrrrrsd......',
    '...drrrsd.......',
    '....dddsd.......',
    '.......dsd......',
    '........dsd.....',
    '.........dsd....',
    '..........dsd...',
    '...........dd...',
    '................',
  ] },
};
