/*
 * art.tiles.js — the world, in 16x16 pieces.
 *
 * Every tile is drawn in theme slots (a highlight, b base, c shade, d outline,
 * e accent) and never in a colour, so the same brick is the orange one in the
 * overworld, the cyan one underground, the grey one in a castle and the white
 * one on a snow level. Ten themes out of one sheet; see palettes.js.
 *
 * The lighting convention is fixed and worth stating once: light comes from
 * the upper left. Highlight on the top and left edges, shade on the bottom and
 * right, outline on the outermost pixel. Break it on one tile and that tile
 * looks like it belongs to a different game.
 */

export const TILE_ART = {
  /* ---------------- Floors, one per terrain family ---------------- */
  ground_soil: { w: 16, h: 16, rows: [
    'aaaaaaaaaaaaaaad',
    'abbbbbbbbbbbbbbd',
    'abbccbbccbbccbbd',
    'abbccbbccbbccbbd',
    'abbbbbbbbbbbbbbd',
    'accbbccbbccbbccd',
    'accbbccbbccbbccd',
    'abbbbbbbbbbbbbbd',
    'abbccbbccbbccbbd',
    'abbccbbccbbccbbd',
    'abbbbbbbbbbbbbbd',
    'accbbccbbccbbccd',
    'accbbccbbccbbccd',
    'abbbbbbbbbbbbbbd',
    'abbccbbccbbccbbd',
    'dddddddddddddddd',
  ] },

  ground_stone: { w: 16, h: 16, rows: [
    'aaaaaaaaaaaaaaad',
    'abbbbbbdbbbbbbcd',
    'abbbbbbdbbbbbbcd',
    'acccccccccccccdd',
    'dddddddddddddddd',
    'abbbdbbbbbbbbbcd',
    'abbbdbbbbbbbbbcd',
    'acccdcccccccccdd',
    'dddddddddddddddd',
    'abbbbbbbbbdbbbcd',
    'abbbbbbbbbdbbbcd',
    'acccccccccdcccdd',
    'dddddddddddddddd',
    'abbbbdbbbbbbbbcd',
    'abbbbdbbbbbbbbcd',
    'dddddddddddddddd',
  ] },

  ground_sand: { w: 16, h: 16, rows: [
    'aaaaaaaaaaaaaaad',
    'abbbbbbbbbbbbbcd',
    'abbbbcbbbbbbbbcd',
    'abbbbbbbbbcbbbcd',
    'acbbbbbbbbbbbbcd',
    'abbbbbbbcbbbbbcd',
    'abbbcbbbbbbbbbcd',
    'abbbbbbbbbbbcbcd',
    'abbbbbbcbbbbbbcd',
    'acbbbbbbbbbbbbcd',
    'abbbbbbbbcbbbbcd',
    'abbbcbbbbbbbbbcd',
    'abbbbbbbbbbcbbcd',
    'abbbbbcbbbbbbbcd',
    'abbbbbbbbbbbbbcd',
    'dddddddddddddddd',
  ] },

  ground_snow: { w: 16, h: 16, rows: [
    'eeeeeeeeeeeeeeee',
    'eeeeeeeeeeeeeeee',
    'aeaeeaeeaeeaeaed',
    'abbbbbbbbbbbbbbd',
    'abbccbbccbbccbbd',
    'accbbccbbccbbccd',
    'abbbbbbbbbbbbbbd',
    'abbccbbccbbccbbd',
    'accbbccbbccbbccd',
    'abbbbbbbbbbbbbbd',
    'abbccbbccbbccbbd',
    'accbbccbbccbbccd',
    'abbbbbbbbbbbbbbd',
    'abbccbbccbbccbbd',
    'accbbccbbccbbccd',
    'dddddddddddddddd',
  ] },

  ground_coral: { w: 16, h: 16, rows: [
    'aabaabbaabbaabad',
    'abbbabbbabbbabbd',
    'abbbbbbbbbbbbbcd',
    'abbcbbbcbbbcbbcd',
    'abbccbbccbbccbcd',
    'accbbccbbccbbccd',
    'abbbbbbbbbbbbbcd',
    'abbccbbccbbccbcd',
    'accbbccbbccbbccd',
    'abbbbbbbbbbbbbcd',
    'abbccbbccbbccbcd',
    'accbbccbbccbbccd',
    'abbbbbbbbbbbbbcd',
    'abbccbbccbbccbcd',
    'accbbccbbccbbccd',
    'dddddddddddddddd',
  ] },

  /* ---------------- Blocks ---------------- */
  brick: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'aaaaaaadaaaaaaad',
    'bbbbbbbdbbbbbbbd',
    'cccccccdcccccccd',
    'dddddddddddddddd',
    'aaadaaaaaaaadaaa',
    'bbbdbbbbbbbbdbbb',
    'cccdccccccccdccc',
    'dddddddddddddddd',
    'aaaaaaadaaaaaaad',
    'bbbbbbbdbbbbbbbd',
    'cccccccdcccccccd',
    'dddddddddddddddd',
    'aaadaaaaaaaadaaa',
    'bbbdbbbbbbbbdbbb',
    'cccdccccccccdccc',
  ] },

  solid: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'daaaaaaaaaaaaaad',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dabbbbbbbbbbbbcd',
    'dccccccccccccccd',
    'dddddddddddddddd',
  ] },

  /* The question block, animated by moving the highlight and dimming the
     glyph. Frame 3 is the same as frame 1, so the cycle is 0-1-2-1. */
  qblock0: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'dabbbbbbbbbbbbad',
    'dbbbbbbbbbbbbbbd',
    'dbbbbbeeeebbbbbd',
    'dbbbbeeeeeebbbbd',
    'dbbbbeebbeebbbbd',
    'dbbbbbbbbeebbbbd',
    'dbbbbbbbeebbbbbd',
    'dbbbbbbeebbbbbbd',
    'dbbbbbbeebbbbbbd',
    'dbbbbbbbbbbbbbbd',
    'dbbbbbbeebbbbbbd',
    'dbbbbbbeebbbbbbd',
    'dbbbbbbbbbbbbbbd',
    'dabbbbbbbbbbbbad',
    'dddddddddddddddd',
  ] },

  qblock1: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'dbbbbbbbbbbbbbbd',
    'dbbbbbbbbbbbbbbd',
    'dbbbbbccccbbbbbd',
    'dbbbbccccccbbbbd',
    'dbbbbccbbccbbbbd',
    'dbbbbbbbbccbbbbd',
    'dbbbbbbbccbbbbbd',
    'dbbbbbbccbbbbbbd',
    'dbbbbbbccbbbbbbd',
    'dbbbbbbbbbbbbbbd',
    'dbbbbbbccbbbbbbd',
    'dbbbbbbccbbbbbbd',
    'dbbbbbbbbbbbbbbd',
    'dbbbbbbbbbbbbbbd',
    'dddddddddddddddd',
  ] },

  qblock2: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'dcbbbbbbbbbbbbcd',
    'dcbbbbbbbbbbbbcd',
    'dcbbbbccccbbbbcd',
    'dcbbbccccccbbbcd',
    'dcbbbccbbccbbbcd',
    'dcbbbbbbbbccbbcd',
    'dcbbbbbbccbbbbcd',
    'dcbbbbbccbbbbbcd',
    'dcbbbbbccbbbbbcd',
    'dcbbbbbbbbbbbbcd',
    'dcbbbbbccbbbbbcd',
    'dcbbbbbccbbbbbcd',
    'dcbbbbbbbbbbbbcd',
    'dcbbbbbbbbbbbbcd',
    'dddddddddddddddd',
  ] },

  qblock_used: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'daccccccccccccad',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'dccccccccccccccd',
    'daccccccccccccad',
    'dddddddddddddddd',
  ] },

  /* An invisible block only becomes a tile once it has been hit, so it needs
     no art of its own — it turns into qblock_used. */

  /* ---------------- Pipes. The lip is the top half of the top two tiles,
     the body is inset two pixels on each side. ---------------- */
  pipe_lip_l: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'daabbbbbbbbbbbbb',
    'daabbbbbbbbbbbbb',
    'daabbbbbbbbbbbbb',
    'daabbbbbbbbbbbbb',
    'daabbbbbbbbbbbbb',
    'daabbbbbbbbbbbbb',
    'dddddddddddddddd',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
  ] },

  pipe_lip_r: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'bbbbbbbbbbbbbccd',
    'bbbbbbbbbbbbbccd',
    'bbbbbbbbbbbbbccd',
    'bbbbbbbbbbbbbccd',
    'bbbbbbbbbbbbbccd',
    'bbbbbbbbbbbbbccd',
    'dddddddddddddddd',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
  ] },

  pipe_body_l: { w: 16, h: 16, rows: [
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
    '..daabbbbbbbbbbb',
  ] },

  pipe_body_r: { w: 16, h: 16, rows: [
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
    'bbbbbbbbbbbccd..',
  ] },

  /* ---------------- Platforms and scenery you can stand on ------------- */
  platform: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'aaaaaaaaaaaaaaad',
    'bbbbbbbbbbbbbbcd',
    'bbbbbbbbbbbbbbcd',
    'ccccccccccccccdd',
    'dddddddddddddddd',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ] },

  mushroom_top: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'daaaaaaaaaaaaaad',
    'dbbbbbbbbbbbbbcd',
    'dbbeebbeebbeebcd',
    'dbbbbbbbbbbbbbcd',
    'dcccccccccccccdd',
    'dddddddddddddddd',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ] },

  mushroom_stem: { w: 16, h: 16, rows: [
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
    '......dccd......',
  ] },

  bridge: { w: 16, h: 16, rows: [
    'dddddddddddddddd',
    'aaaaaaaaaaaaaaad',
    'bbbbbbbbbbbbbbcd',
    'cccccccccccccccd',
    'dddddddddddddddd',
    '...dd......dd...',
    '...dd......dd...',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ] },

  /* Bits of a broken brick. Four of these fly out of every block a big
     player heads through, so they are drawn in theme slots and match
     whatever the level's bricks look like. */
  debris: { w: 8, h: 8, rows: [
    '.dddddd.',
    'daaaaaad',
    'dabbbbad',
    'dabbbbad',
    'dabbbbad',
    'dabbbbad',
    'daccccad',
    '.dddddd.',
  ] },

  tree_top: { w: 16, h: 16, rows: [
    'eeeeeeeeeeeeeeee',
    'eeeeeeeeeeeeeeee',
    'eeeeeeeeeeeeeeee',
    'dddddddddddddddd',
    'abbbbbbbbbbbbbcd',
    'abbbbbbbbbbbbbcd',
    'accccccccccccccd',
    'dddddddddddddddd',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ] },

  log: { w: 16, h: 16, rows: [
    '....dbbbbbbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
    '....dbccccbd....',
  ] },

  cloud_block: { w: 16, h: 16, rows: [
    '..dddd....dddd..',
    '.deeeed..deeeed.',
    'deeeeeeddeeeeeed',
    'deeeeeeeeeeeeeed',
    'deeeeeeeeeeeeeed',
    'daaaaaaaaaaaaaad',
    'dbbbbbbbbbbbbbbd',
    'dddddddddddddddd',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ] },

  /* ---------------- Hazards and liquids ---------------- */
  lava0: { w: 16, h: 16, rows: [
    'eeee..eeeee..eee',
    'eeeeeeeeeeeeeeee',
    'aaeeaaaaeeaaaaee',
    'aaaaaaaaaaaaaaaa',
    'aaaaaaaaaaaaaaaa',
    'baaabbbaaabbbaaa',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'cbbbcccbbbcccbbb',
    'cccccccccccccccc',
    'cccccccccccccccc',
    'cccccccccccccccc',
    'cccccccccccccccc',
    'cccccccccccccccc',
    'cccccccccccccccc',
  ] },

  lava1: { w: 16, h: 16, rows: [
    'ee..eeeee..eeeee',
    'eeeeeeeeeeeeeeee',
    'aaaaeeaaaaeeaaaa',
    'aaaaaaaaaaaaaaaa',
    'aaaaaaaaaaaaaaaa',
    'bbbaaabbbaaabbba',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'cccbbbcccbbbcccb',
    'cccccccccccccccc',
    'cccccccccccccccc',
    'cccccccccccccccc',
    'cccccccccccccccc',
    'cccccccccccccccc',
    'cccccccccccccccc',
  ] },

  water_top0: { w: 16, h: 16, rows: [
    'aaaa....aaaa....',
    '....aaaa....aaaa',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
  ] },

  water_top1: { w: 16, h: 16, rows: [
    '....aaaa....aaaa',
    'aaaa....aaaa....',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
    'bbbbbbbbbbbbbbbb',
  ] },

  spike: { w: 16, h: 16, rows: [
    '................',
    '................',
    '................',
    '...a.......a....',
    '..aad.....aad...',
    '..abd.....abd...',
    '.aabbd...aabbd..',
    '.abbbd...abbbd..',
    'aabbbbd.aabbbbd.',
    'abbbbcd.abbbbcd.',
    'abbbccd.abbbccd.',
    'abbcccd.abbcccd.',
    'accccccdaccccccd',
    'ccccccccccccccdd',
    'dddddddddddddddd',
    'dddddddddddddddd',
  ] },

  vine: { w: 16, h: 16, rows: [
    '......dbbd......',
    '...dbbdbbd......',
    '..dbbbdbbd......',
    '..dbbddbbd......',
    '...ddddbbd......',
    '......dbbd......',
    '......dbbdbbd...',
    '......dbbdbbbd..',
    '......dbbddbbbd.',
    '......dbbd.ddd..',
    '......dbbd......',
    '...dbbdbbd......',
    '..dbbbdbbd......',
    '..dbbddbbd......',
    '...ddddbbd......',
    '......dbbd......',
  ] },

  /* ---------------- The end of the level ---------------- */
  flag_ball: { w: 16, h: 16, rows: [
    '................',
    '................',
    '.....eeeeee.....',
    '....eeaaaaee....',
    '...eeaaaaaaee...',
    '...eaaaaaaaae...',
    '...eaaaaaaaae...',
    '...eaaaaaaaae...',
    '...eeaaaaaaee...',
    '....eeaaaaee....',
    '.....eeeeee.....',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
  ] },

  flagpole: { w: 16, h: 16, rows: [
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
    '.......ee.......',
  ] },

  flag: { w: 16, h: 16, rows: [
    '................',
    'ddddddddddddd...',
    'daaaaaaaaaaad...',
    'daadaaaaaaaad...',
    'daaddaaaaaaad...',
    'daadddaaaaaad...',
    'daaddddaaaaad...',
    'daadddddaaaad...',
    'daaddddaaaaad...',
    'daadddaaaaaad...',
    'daaddaaaaaaad...',
    'daadaaaaaaaad...',
    'daaaaaaaaaaad...',
    'ddddddddddddd...',
    '................',
    '................',
  ] },

  castle_brick: { w: 16, h: 16, rows: [
    'aaaaaaadaaaaaaad',
    'bbbbbbbdbbbbbbbd',
    'bbbbbbbdbbbbbbbd',
    'dddddddddddddddd',
    'aaadaaaaaaaadaaa',
    'bbbdbbbbbbbbdbbb',
    'bbbdbbbbbbbbdbbb',
    'dddddddddddddddd',
    'aaaaaaadaaaaaaad',
    'bbbbbbbdbbbbbbbd',
    'bbbbbbbdbbbbbbbd',
    'dddddddddddddddd',
    'aaadaaaaaaaadaaa',
    'bbbdbbbbbbbbdbbb',
    'bbbdbbbbbbbbdbbb',
    'dddddddddddddddd',
  ] },

  castle_door: { w: 16, h: 16, rows: [
    'aaaaaaadaaaaaaad',
    'bbbdddddddddbbbd',
    'bbdddddddddddbbd',
    'bdddddddddddddbd',
    'adddddddddddddad',
    'bdddddddddddddbd',
    'bdddddddddddddbd',
    'dddddddddddddddd',
    'addddddddddddddd',
    'bdddddddddddddbd',
    'bdddddddddddddbd',
    'dddddddddddddddd',
    'addddddddddddddd',
    'bdddddddddddddbd',
    'bdddddddddddddbd',
    'dddddddddddddddd',
  ] },

  castle_window: { w: 16, h: 16, rows: [
    'aaaaaaadaaaaaaad',
    'bbbbbbbdbbbbbbbd',
    'bbbbbbbdbbbbbbbd',
    'dddddddddddddddd',
    'aaadddddddddddaa',
    'bbbdddddddddddbb',
    'bbbdddddddddddbb',
    'ddddddddddddddda',
    'aaadddddddddddaa',
    'bbbdddddddddddbb',
    'bbbdddddddddddbb',
    'dddddddddddddddd',
    'aaadaaaaaaaadaaa',
    'bbbdbbbbbbbbdbbb',
    'bbbdbbbbbbbbdbbb',
    'dddddddddddddddd',
  ] },

  castle_top: { w: 16, h: 16, rows: [
    'ddd..ddd..ddd...',
    'aaa..aaa..aaa...',
    'bbb..bbb..bbb...',
    'bbb..bbb..bbb...',
    'ddddddddddddd...',
    'aaadaaaaaaaad...',
    'bbbdbbbbbbbbd...',
    'bbbdbbbbbbbbd...',
    'ddddddddddddd...',
    'aaaaaaadaaaaa...',
    'bbbbbbbdbbbbb...',
    'bbbbbbbdbbbbb...',
    'ddddddddddddd...',
    '................',
    '................',
    '................',
  ] },
};

/*
 * Horizontal pipes are the vertical ones turned a quarter turn — derived
 * rather than drawn, so a change to the pipe shading cannot leave the two
 * orientations disagreeing about what a pipe looks like.
 *
 * The turn is clockwise and then mirrored, not counter-clockwise, and the
 * difference matters: a quarter turn clockwise carries the lit left edge onto
 * the top, which is where light comes from everywhere else in this game. The
 * mirror afterwards puts the mouth back on the left, facing a player walking
 * into it, without disturbing the lighting.
 */
function rotateCW(art) {
  const rows = [];
  for (let y = 0; y < art.w; y++) {
    let row = '';
    for (let x = 0; x < art.h; x++) row += art.rows[art.h - 1 - x][y];
    rows.push(row);
  }
  return { w: art.h, h: art.w, rows };
}

function mirrorX(art) {
  return { w: art.w, h: art.h, rows: art.rows.map((r) => r.split('').reverse().join('')) };
}

const turned = (name) => mirrorX(rotateCW(TILE_ART[name]));

TILE_ART.pipe_h_lip_t = turned('pipe_lip_l');
TILE_ART.pipe_h_lip_b = turned('pipe_lip_r');
TILE_ART.pipe_h_body_t = turned('pipe_body_l');
TILE_ART.pipe_h_body_b = turned('pipe_body_r');
