/* manifest.js — GENERATED by tools/lm-train.mjs. Do not edit by hand.
 *
 * What the trained model in this directory is, without loading it.
 */

export const MODEL = {
  "file": "laken.js",
  "source": "corpus:log",
  "characters": 32650,
  "steps": 400,
  "heldOutLoss": 0.3468,
  "vocab": 44,
  "context": 8,
  "embed": 24,
  "hidden": 128,
  "bytes": 305790,
  "trainedAt": "2026-08-21T01:04:19.806Z"
};
