/* manifest.js — GENERATED by tools/lm-train.mjs. Do not edit by hand.
 *
 * What the trained model in this directory is, without loading it.
 */

export const MODEL = {
  "file": "laken.js",
  "source": "corpus:both",
  "characters": 2261604,
  "steps": 300000,
  "heldOutLoss": 2.5052,
  "vocab": 154,
  "context": 12,
  "embed": 24,
  "hidden": 256,
  "bytes": 1039694,
  "trainedAt": "2026-08-21T23:02:14.624Z"
};
