#!/usr/bin/env node
/*
 * dailyspark-fonts.mjs — embeds DailySpark's two faces as base64.
 *
 * Same job as tools/fetch-fonts.js next door, different families and a separate
 * output file. It is a second script rather than a flag on the first because
 * the two apps have no reason to share a font budget: FitAI needs a mono for
 * its numbers and this one does not, and DailySpark needs a serif that FitAI
 * would only carry as dead weight.
 *
 * The serif matters here more than usual. The spark's own text is the one place
 * in the app that uses it, and it is what makes the card read as a page from a
 * book rather than as a notification — which is the entire visual thesis.
 *
 *   node tools/dailyspark-fonts.mjs
 *
 * Fonts are licensed under the SIL Open Font License 1.1.
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'dailyspark/src/styles/fonts.css');

const CSS_URL = 'https://fonts.googleapis.com/css2'
  + '?family=Assistant:wght@400;600;700'
  + '&family=Frank+Ruhl+Libre:wght@500;700'
  + '&display=swap';

// A modern desktop UA is what makes Google serve woff2 rather than ttf.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const KEEP_SUBSETS = new Set(['hebrew', 'latin']);

async function get(url, asBuffer) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
}

const css = await get(CSS_URL, false);

const blocks = [...css.matchAll(/\/\*\s*([^*]+?)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g)];
if (!blocks.length) throw new Error('could not parse any @font-face blocks');

const out = [
  '/* fonts.css — GENERATED by tools/dailyspark-fonts.mjs. Do not edit by hand.',
  ' *',
  ' * Hebrew and Latin subsets of Assistant (interface) and Frank Ruhl Libre',
  ' * (the spark text itself), embedded as base64 so the app renders identically',
  ' * offline and inside the single-file build.',
  ' *',
  ' * Regenerate with: node tools/dailyspark-fonts.mjs',
  ' * Fonts are licensed under the SIL Open Font License 1.1.',
  ' */',
  '',
];

let kept = 0;
let bytes = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP_SUBSETS.has(subset.trim())) continue;
  const url = /url\((https:\/\/[^)]+)\)/.exec(block);
  if (!url) continue;

  const buf = await get(url[1], true);
  bytes += buf.length;
  kept += 1;

  const family = /font-family:\s*'([^']+)'/.exec(block);
  const weight = /font-weight:\s*([^;]+);/.exec(block);
  const style = /font-style:\s*([^;]+);/.exec(block);
  const range = /unicode-range:\s*([^;]+);/.exec(block);

  out.push('@font-face {');
  out.push(`  font-family: '${family ? family[1] : 'unknown'}';`);
  out.push(`  font-style: ${style ? style[1].trim() : 'normal'};`);
  out.push(`  font-weight: ${weight ? weight[1].trim() : '400'};`);
  out.push('  font-display: swap;');
  out.push(`  src: url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2');`);
  if (range) out.push(`  unicode-range: ${range[1].trim()};`);
  out.push('}');
  out.push('');
}

writeFileSync(OUT, out.join('\n'));
console.log(`dailyspark/src/styles/fonts.css — ${kept} faces, ${Math.round(bytes / 1024)} KB of font data`);
