#!/usr/bin/env node
/*
 * fetch-fonts.js — downloads the Hebrew and Latin subsets of the three app
 * fonts and writes them into src/styles/fonts.css as base64 @font-face rules.
 *
 * Run this once (or when the font stack changes). The generated file is
 * committed, so neither the app nor the single-file build ever needs the
 * network — which is the whole point of a file you can open on a plane.
 *
 * Usage: node tools/fetch-fonts.js
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'src/styles/fonts.css');

const CSS_URL = 'https://fonts.googleapis.com/css2'
  + '?family=Secular+One'
  + '&family=Assistant:wght@400;600;700'
  + '&family=IBM+Plex+Mono:wght@400;600'
  + '&display=swap';

// A modern desktop UA is what makes Google serve woff2 rather than ttf.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const KEEP_SUBSETS = new Set(['hebrew', 'latin']);

async function get(url, asBuffer) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asBuffer ? Buffer.from(await res.arrayBuffer()) : res.text();
}

const css = await get(CSS_URL, false);

// Google's CSS emits a /* subset */ comment before each @font-face block.
const blocks = [...css.matchAll(/\/\*\s*([^*]+?)\s*\*\/\s*(@font-face\s*\{[\s\S]*?\})/g)];
if (!blocks.length) throw new Error('could not parse any @font-face blocks');

const out = [
  '/* fonts.css — GENERATED by tools/fetch-fonts.js. Do not edit by hand.',
  ' *',
  ' * Hebrew and Latin subsets of Secular One, Assistant and IBM Plex Mono,',
  ' * embedded as base64 so the app renders identically offline and inside the',
  ' * single-file build. Regenerate with: node tools/fetch-fonts.js',
  ' *',
  ' * Fonts are licensed under the SIL Open Font License 1.1.',
  ' */',
  '',
];

let kept = 0;
let bytes = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP_SUBSETS.has(subset.trim())) continue;
  const url = /url\((https:\/\/[^)]+)\)/.exec(block);
  if (!url) continue;

  const buf = await get(url[1], true);
  bytes += buf.length;
  kept++;

  const family = /font-family:\s*'([^']+)'/.exec(block);
  const weight = /font-weight:\s*([^;]+);/.exec(block);
  const style = /font-style:\s*([^;]+);/.exec(block);
  const range = /unicode-range:\s*([^;]+);/.exec(block);

  out.push('@font-face {');
  out.push(`  font-family: '${family ? family[1] : 'unknown'}';`);
  out.push(`  font-style: ${style ? style[1].trim() : 'normal'};`);
  out.push(`  font-weight: ${weight ? weight[1].trim() : '400'};`);
  out.push('  font-display: swap;');
  out.push(`  src: url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2');`);
  if (range) out.push(`  unicode-range: ${range[1].trim()};`);
  out.push('}');
  out.push('');
}

writeFileSync(OUT, out.join('\n'));
console.log(`src/styles/fonts.css — ${kept} faces, ${Math.round(bytes / 1024)} KB of font data`);
