#!/usr/bin/env node
/*
 * lm-corpus.mjs — assembles what the writing agents produced into the two
 * corpora the playground and the trainer load.
 *
 * A hundred agents each wrote one slice of training text into its own file:
 * seventy-five slices of code across a dozen languages, twenty-five of Hebrew
 * questions and answers. This turns that pile into two ES modules, because the
 * page that has to read them runs under `connect-src 'none'` and cannot fetch a
 * .txt file — a module it can import, since that is script-src, and script-src
 * is 'self'.
 *
 * Each slice becomes one JSON string on one line, so a re-run of a single agent
 * shows up in a diff as a single changed line rather than as a rewritten file.
 *
 * Usage:
 *   node tools/lm-corpus.mjs --from <dir>     # build the modules from a slice directory
 *   node tools/lm-corpus.mjs --verify         # load the built modules and report
 *   node tools/lm-corpus.mjs --audit          # parse every code snippet with a real parser
 */

import { readdir, readFile, writeFile, mkdir, mkdtemp, rm } from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { resolve, dirname, join, basename } from 'node:path';
import { safeSvg } from '../lm/src/picture.js';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';

const run = promisify(execFile);
const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'lm/src/corpora');

const arg = (name, fallback = null) => {
  const i = process.argv.indexOf(`--${name}`);
  return i < 0 ? fallback : (process.argv[i + 1] ?? true);
};

const MIN_SLICE = 1200;      // anything shorter is a failed agent, not a slice
const SEPARATOR = '\n\n';

/**
 * The families a slice can belong to, by the prefix its writer was given.
 *
 * Each becomes one module, and the table is the only place that knows the
 * mapping — a slice whose prefix is not here is reported rather than silently
 * dropped, which is what used to happen: the first run after the picture
 * writers finished put thirty-two thousand characters of drawings nowhere at
 * all, and said nothing.
 */
const FAMILIES = [
  { prefix: 'code-', module: 'code', label: 'code across a dozen languages' },
  { prefix: 'gen-', module: 'general', label: 'Hebrew questions and answers' },
  { prefix: 'chat-', module: 'chat', label: 'short Hebrew exchanges, the shape the chat box speaks' },
  { prefix: 'art-', module: 'pictures', label: 'character art and small SVG' },
  { prefix: 'svg-', module: 'pictures', label: 'character art and small SVG' },
];

const familyOf = (id) => FAMILIES.find((f) => id.startsWith(f.prefix)) || null;

/* Language of a slice, from its file name: code-07-js.txt → js, art-03 → art. */
const kindOf = (name) => {
  if (!name.startsWith('code-')) return name.replace(/-\d+.*$/, '');
  return name.replace(/^code-\d+-/, '').replace(/\.txt$/, '');
};

/**
 * What an agent writes and what a corpus needs are not quite the same thing.
 * This is deliberately conservative — it removes wrappers and whitespace noise
 * and nothing else. Anything that looks like a real failure (a slice that is
 * mostly apology, a slice that is 200 characters long) is reported rather than
 * patched, because a corpus quietly repaired by a regular expression is a
 * corpus nobody can reason about.
 */
function clean(text, { language }, report) {
  let out = text.replace(/^﻿/, '').replace(/\r\n/g, '\n').replace(/\r/g, '\n');

  /* Bytes that are not text. One writer, asked for a string sanitiser, wrote
   * the control characters into its regular expression literally instead of as
   * escapes — so the slice really did contain a NUL. Two characters in eighty
   * thousand, and both of them would have become tokens in the vocabulary: an
   * invisible column in every weight matrix, for a character no text has. Tabs
   * and newlines stay; everything else below U+0020, and U+007F, goes. */
  const control = (out.match(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g) || []).length;
  if (control) {
    out = out.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, '');
    report.control += control;
  }

  /* A whole slice wrapped in one fence: unwrap it. Markdown slices are supposed
   * to contain fences, so they are left alone. */
  if (language !== 'md') {
    const fences = out.split('\n').filter((l) => /^\s*```/.test(l)).length;
    if (fences === 2 && /^\s*```/.test(out.trimStart())) {
      out = out.replace(/^\s*```[^\n]*\n/, '').replace(/\n\s*```\s*$/, '\n');
    }
  }

  out = out.split('\n').map((l) => l.replace(/[ \t]+$/, '')).join('\n');
  out = out.replace(/\n{3,}/g, '\n\n').trim();
  return out ? `${out}\n` : '';
}

const module_ = (name, parts, note) => `/* ${name}.js — GENERATED by tools/lm-corpus.mjs. Do not edit by hand.
 *
 * ${note}
 *
 * One JSON string per writer, in order, joined by a blank line. Imported
 * dynamically by lm/src/main.js so that choosing a corpus costs a download only
 * when it is chosen, and imported directly by tools/lm-train.mjs.
 */

export const PARTS = [
${parts.map((p) => JSON.stringify(p)).join(',\n')},
];

/* The default export is the slices in the order they were written, which is
 * grouped by language. lm/src/corpora/index.js does not use it — it shuffles
 * PARTS first, for reasons explained there. */
export default PARTS.join(${JSON.stringify(SEPARATOR)});
`;

async function build(dir) {
  const from = resolve(ROOT, dir);
  const names = (await readdir(from)).filter((n) => n.endsWith('.txt')).sort();
  const slices = [];
  const rejected = [];
  const report = { control: 0 };

  for (const name of names) {
    const raw = await readFile(join(from, name), 'utf8');
    const language = kindOf(name);
    const text = clean(raw, { language }, report);
    const id = basename(name, '.txt');
    if (text.length < MIN_SLICE) { rejected.push({ id, characters: text.length }); continue; }
    slices.push({ id, language, text, characters: text.length, lines: text.split('\n').length });
  }

  await mkdir(OUT, { recursive: true });

  const orphans = slices.filter((s) => !familyOf(s.id));
  const modules = [...new Set(FAMILIES.map((f) => f.module))];
  const total = (list) => list.reduce((n, s) => n + s.characters, 0) + Math.max(0, list.length - 1) * SEPARATOR.length;

  const manifest = {};
  for (const name of modules) {
    const family = FAMILIES.filter((f) => f.module === name);
    const mine = slices.filter((s) => family.some((f) => s.id.startsWith(f.prefix)));
    await writeFile(join(OUT, `${name}.js`), module_(name, mine.map((s) => s.text),
      `${mine.length} slices of ${family[0].label}, one per writing agent.`));
    manifest[name] = {
      writers: mine.length,
      characters: total(mine),
      parts: mine.map((s) => ({ id: s.id, language: s.language, characters: s.characters })),
    };
  }

  await writeFile(join(OUT, 'manifest.js'), `/* manifest.js — GENERATED by tools/lm-corpus.mjs. Do not edit by hand.
 *
 * Who wrote what. The page reads the writer counts and character totals to
 * label the corpus picker; the rest is provenance — one line per agent, so a
 * slice that turns out to be junk can be traced back to the writer that made it
 * and regenerated on its own.
 */

export const MANIFEST = ${JSON.stringify(manifest, null, 2)};
`);

  for (const name of modules) {
    console.log(`${name.padEnd(9)} ${String(manifest[name].writers).padStart(2)} writers, ${manifest[name].characters.toLocaleString().padStart(9)} characters`);
  }
  if (orphans.length) {
    console.log(`\n⚠ ${orphans.length} slice(s) belong to no family and were left out: ${orphans.map((o) => o.id).join(', ')}`);
    process.exitCode = 1;
  }
  if (report.control) console.log(`stripped ${report.control} control character(s) that were never text`);
  if (rejected.length) {
    console.log(`\nrejected ${rejected.length} slice(s) under ${MIN_SLICE} characters:`);
    for (const r of rejected) console.log(`  ${r.id}: ${r.characters}`);
  }
  const languages = [...new Set(slices.map((s) => s.language))].sort();
  console.log(`\nkinds: ${languages.join(' ')}`);
  return { manifest, rejected };
}

/**
 * Load the built corpora and check them against their own manifest.
 *
 * Worth being clear about what this can and cannot catch: the manifest is
 * written by the same build that writes the modules, so agreeing with it proves
 * they have not drifted apart since — a half-finished rebuild, an edited
 * module, a module from one build sitting beside a manifest from another — and
 * proves nothing about whether that build was right. The format checks below
 * are the part that looks at the text itself.
 */
async function verify() {
  const { MANIFEST } = await import(pathToFileURL(join(OUT, 'manifest.js')));
  const problems = [];
  const loaded = {};

  for (const name of Object.keys(MANIFEST)) {
    const mod = await import(pathToFileURL(join(OUT, `${name}.js`)));
    loaded[name] = mod.default;
  }

  const look = (name, text, expected) => {
    const chars = new Set(text);
    if (expected !== null && text.length !== expected) problems.push(`${name}: ${text.length} characters, manifest says ${expected}`);
    if (/�/.test(text)) problems.push(`${name}: holds a replacement character — something was decoded wrong`);
    if (/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(text)) problems.push(`${name}: holds control characters`);
    const longest = text.split('\n').reduce((m, l) => Math.max(m, l.length), 0);
    console.log(`${name.padEnd(9)} ${text.length.toLocaleString().padStart(9)} characters · ${String(chars.size).padStart(3)} distinct · longest line ${longest}`);
    if (longest > 4000) problems.push(`${name}: a line of ${longest} characters, which is not text anyone wrote`);
  };

  for (const [name, text] of Object.entries(loaded)) look(name, text, MANIFEST[name].characters);
  const everything = Object.values(loaded).join(SEPARATOR);
  look('together', everything, null);

  /* Each family has a shape it is supposed to hold, and holding it is the whole
   * reason a model this small can do anything with it. */
  const questions = ((loaded.general || '') + (loaded.chat || '')).match(/^ש: /gm) || [];
  const answers = ((loaded.general || '') + (loaded.chat || '')).match(/^ת: /gm) || [];
  console.log(`\nquestion and answer pairs: ${questions.length} questions, ${answers.length} answers`);
  if (Math.abs(questions.length - answers.length) > questions.length * 0.02) {
    problems.push(`questions and answers do not pair up: ${questions.length} vs ${answers.length}`);
  }
  if (questions.length < 300) problems.push(`only ${questions.length} question and answer pairs`);

  if (loaded.pictures) {
    const titles = (loaded.pictures.match(/^\[[^\]\n]{1,40}\]$/gm) || []).length;
    const svgs = (loaded.pictures.match(/<svg viewBox="0 0 24 24">/g) || []).length;
    const closed = (loaded.pictures.match(/<\/svg>/g) || []).length;
    console.log(`pictures: ${titles} character drawings, ${svgs} vector drawings`);
    if (titles < 50) problems.push(`only ${titles} character drawings under a [name] heading`);
    if (svgs < 50) problems.push(`only ${svgs} vector drawings`);
    if (svgs !== closed) problems.push(`${svgs} SVG openings against ${closed} closings`);

    /* The corpus and the thing that will draw it, checked against each other.
     * The page renders what the model writes through one filter — anything with
     * a script, an external reference or a tag that is not a shape is refused —
     * and a corpus teaching markup that filter rejects would be teaching the
     * model to produce pictures the page will not show. */
    const written = loaded.pictures.match(/<svg[\s\S]*?<\/svg>/g) || [];
    const drawable = written.filter((one) => safeSvg(one) !== null);
    console.log(`          ${drawable.length}/${written.length} of them pass the filter the page draws through`);
    if (written.length && drawable.length < written.length) {
      problems.push(`${written.length - drawable.length} SVG(s) in the corpus would be refused by the page's own renderer`);
    }
  }

  if (problems.length) {
    console.error(`\n✗ ${problems.length} problem(s)`);
    for (const p of problems) console.error(`  ${p}`);
    process.exitCode = 1;
    return;
  }
  console.log('\n✓ every corpus loads, matches its manifest, and holds its shape');
}

/**
 * Parse every code snippet with the real parser for its language.
 *
 * The agents were asked for code that compiles, and "asked for" is not
 * evidence. Slices are split back into the snippets they were assembled from,
 * and each one goes to the tool a developer of that language would reach for:
 * node, python, bash, gofmt, rustfmt, gcc, javac, the TypeScript parser, a YAML
 * loader, JSON.parse.
 *
 * Failures are separated into two kinds, because they mean opposite things. A
 * snippet whose syntax is wrong is a blemish in the corpus. A snippet that
 * parses but names a sibling — `#include "list.h"`, `mod shapes;`, a class from
 * the file above it — is correct code being asked to stand alone, which is the
 * auditor's doing and not the writer's. Counting the second kind as a failure
 * would understate a corpus that is fine; counting it as a pass without saying
 * so would overstate one.
 *
 * The result is printed rather than asserted: this is training text for a model
 * that learns characters, so a snippet that does not parse is a blemish and not
 * a failure — but an unmeasured blemish is how a corpus of plausible-looking
 * nonsense gets shipped.
 */
async function audit() {
  const code = (await import(pathToFileURL(join(OUT, 'code.js')))).default;
  const dir = await mkdtemp(join(tmpdir(), 'lm-audit-'));

  /* Every writer was told to head each snippet with a comment naming a file
   * path, and every writer did — so the corpus can be split back into the files
   * it was assembled from, and each one handed to the parser that owns its
   * extension.
   *
   * Dotfiles are files (.eslintrc.json), and one writer allowed itself a
   * parenthetical after the path. Both used to fall through this pattern, which
   * merged the snippet into the one before it — and two JSON documents in one
   * file is a parse error the corpus never contained. Three of the six failures
   * this tool first reported were that, and none of them were the corpus. A
   * file with no extension at all — Dockerfile, Makefile — did the same thing
   * across a slice boundary, which is how a workflow file came to be reported
   * as broken YAML: it had swallowed the Dockerfile that followed it. */
  const BARE = 'Dockerfile|Makefile|Procfile|Gemfile|Rakefile|Jenkinsfile|LICENSE|CHANGELOG|Vagrantfile';
  const NAME = `(?:[.\\w@][\\w./@-]*\\.\\w{1,5}|(?:[\\w./@-]+\\/)?(?:${BARE})(?:\\.[\\w-]+)?|\\.[\\w-]+)`;
  const HEADER = new RegExp(
    `^(?:\\/\\/|#|--|;)[ \\t]*(${NAME})(?:[ \\t]+\\([^)]*\\))?[ \\t]*$`
    + `|^(?:\\/\\*|<!--)[ \\t]*(${NAME})(?:[ \\t]+\\([^)]*\\))?[ \\t]*(?:\\*\\/|-->)[ \\t]*$`,
  );

  /* One writer's whole slice is patches, and a patch is headed by the path of
   * the file it changes. Handing `diff --git a/x.py` to python is a failure
   * that says nothing about the corpus — the hunk is exactly what was asked
   * for. */
  const isPatch = (body) => /^diff --git |^--- a\//m.test(body.split('\n').slice(0, 4).join('\n'));

  const snippets = [];
  let current = null;
  for (const line of code.split('\n')) {
    const head = line.match(HEADER);
    if (head) {
      if (current) snippets.push(current);
      current = { path: head[1] || head[2], body: [] };
    } else if (current) {
      current.body.push(line);
    }
  }
  if (current) snippets.push(current);

  /* TypeScript is checked through the compiler's own parser rather than by
   * running tsc, because tsc would also resolve imports and report every
   * missing module in a snippet that was never meant to have its neighbours —
   * type errors about a world that does not exist, not syntax errors about the
   * text. Syntactic diagnostics are exactly the question being asked. */
  let ts = null;
  try {
    ts = createRequire(join('/opt/node22/lib/node_modules/', 'x.js'))('typescript');
  } catch {
    try { ts = createRequire(import.meta.url)('typescript'); } catch { /* reported as unchecked */ }
  }

  const file = async (name, body) => {
    const path = join(dir, name);
    await writeFile(path, `${body}\n`);
    return path;
  };

  /* A compiler complaining that it cannot find a sibling file, class or module
   * is answering a question nobody asked: these snippets were written as a set
   * and are being parsed one at a time. Everything else counts. */
  const UNRESOLVED = /cannot find symbol|package [\w.]+ does not exist|does not exist|No such file or directory|failed to resolve mod|unresolved import|cannot find (?:type|value|crate|module)|file not found for module/i;
  const SYNTAX = /expected|illegal|unexpected|invalid syntax|reached end of file|unterminated|missing|malformed|not a statement|unclosed/i;

  /* javac writes a line about the trust store on every run in this container,
   * which is neither an error nor interesting. */
  const clean_ = (text) => String(text || '')
    .split('\n')
    .filter((l) => l.trim() && !/^Picked up JAVA_TOOL_OPTIONS/.test(l))
    .join('\n');

  const classify = (err) => {
    const text = clean_(err.stderr || err.message);
    /* gcc opens with the function it was in, javac with a file and line; the
     * line that says "error:" is the one worth printing. */
    const lines = text.split('\n').filter((l) => l.trim());
    const first = lines.find((l) => /error(:|\[)/i.test(l)) || lines[0] || 'failed';
    /* Syntax wins where both appear: a file that fails to parse also fails to
     * resolve, and the parse error is the real one. */
    if (SYNTAX.test(text) && !/does not exist|No such file/i.test(first)) return { kind: 'syntax', line: first };
    if (UNRESOLVED.test(text)) return { kind: 'unresolved', line: first };
    return { kind: 'syntax', line: first };
  };

  /* Each checker is the tool a developer of that language would reach for to
   * ask "does this parse", and nothing heavier: gofmt and rustfmt both refuse
   * a file they cannot parse, gcc has a flag for exactly this question, and
   * javac is given a filename matching whatever public type it declares,
   * because it will not compile the file otherwise. */
  const CHECKERS = {
    js: async (b, i) => run('node', ['--check', await file(`s${i}.mjs`, b)]),
    mjs: async (b, i) => run('node', ['--check', await file(`s${i}.mjs`, b)]),
    cjs: async (b, i) => run('node', ['--check', await file(`s${i}.cjs`, b)]),
    py: async (b, i) => run('python3', ['-m', 'py_compile', await file(`s${i}.py`, b)]),
    sh: async (b, i) => run('bash', ['-n', await file(`s${i}.sh`, b)]),
    bash: async (b, i) => run('bash', ['-n', await file(`s${i}.sh`, b)]),
    json: async (b) => { JSON.parse(b); },
    go: async (b, i) => run('gofmt', ['-e', await file(`s${i}.go`, b)]),
    rs: async (b, i) => run('rustfmt', ['--edition', '2021', '--emit', 'stdout', await file(`s${i}.rs`, b)]),
    /* -I dir, because every .h snippet in the corpus is written into that
     * directory under its own basename before anything is checked: a C file
     * that includes its own header is not missing anything, the auditor was. */
    c: async (b, i) => run('gcc', ['-fsyntax-only', '-w', `-I${dir}`, await file(`s${i}.c`, b)]),
    h: async (b, i) => run('gcc', ['-fsyntax-only', '-w', `-I${dir}`, '-x', 'c', await file(`s${i}.h`, b)]),
    yml: async (b, i) => run('python3', ['-c', 'import sys,yaml;list(yaml.safe_load_all(open(sys.argv[1])))', await file(`s${i}.yml`, b)]),
    yaml: async (b, i) => run('python3', ['-c', 'import sys,yaml;list(yaml.safe_load_all(open(sys.argv[1])))', await file(`s${i}.yml`, b)]),
    java: async (b, i) => {
      const declared = b.match(/public\s+(?:final\s+|abstract\s+)?(?:class|interface|enum|record)\s+(\w+)/);
      const name = declared ? `${declared[1]}.java` : `S${i}.java`;
      return run('javac', ['-nowarn', '-d', dir, await file(name, b)]);
    },
  };
  if (ts) {
    const parse = (b, name) => {
      const source = ts.createSourceFile(name, b, ts.ScriptTarget.Latest, true,
        name.endsWith('.tsx') ? ts.ScriptKind.TSX : ts.ScriptKind.TS);
      const errors = source.parseDiagnostics || [];
      if (errors.length) {
        const first = errors[0];
        throw new Error(ts.flattenDiagnosticMessageText(first.messageText, ' '));
      }
    };
    CHECKERS.ts = async (b, i) => parse(b, `s${i}.ts`);
    CHECKERS.tsx = async (b, i) => parse(b, `s${i}.tsx`);
  }

  /* Headers first, under their real names, so the C files that include them can
   * be parsed as written. */
  for (const snippet of snippets) {
    const base = snippet.path.split('/').pop() || '';
    if (base.endsWith('.h')) await file(base, snippet.body.join('\n').trim());
  }

  const seen = {};
  const results = {};
  let index = 0;

  for (const snippet of snippets) {
    const body = snippet.body.join('\n').trim();
    const base = snippet.path.split('/').pop() || snippet.path;
    const ext = isPatch(body)
      ? 'patch'
      : (base.includes('.') ? base.split('.').pop() : base).toLowerCase();
    seen[ext] = (seen[ext] || 0) + 1;
    if (!CHECKERS[ext] || body.length < 60) continue;

    results[ext] ??= { total: 0, ok: 0, unresolved: 0, failures: [] };
    results[ext].total++;
    try {
      await CHECKERS[ext](body, index++);
      results[ext].ok++;
    } catch (err) {
      const { kind, line } = classify(err);
      if (kind === 'unresolved') results[ext].unresolved++;
      else results[ext].failures.push(`${snippet.path}: ${line}`);
    }
  }

  console.log(`${snippets.length} snippets in the code corpus`);
  let total = 0, ok = 0, unresolved = 0;
  for (const [ext, r] of Object.entries(results).sort()) {
    total += r.total; ok += r.ok; unresolved += r.unresolved;
    const share = Math.round(((r.ok + r.unresolved) / r.total) * 100);
    console.log(`  .${ext.padEnd(5)} ${String(r.ok).padStart(3)}/${String(r.total).padEnd(3)} parse`
      + (r.unresolved ? ` · ${r.unresolved} more parse but name a sibling snippet` : '')
      + ` · ${share}% clean`);
    for (const f of r.failures.slice(0, 4)) console.log(`         ✗ ${f.slice(0, 130)}`);
  }
  const unchecked = Object.entries(seen).filter(([ext]) => !CHECKERS[ext]);
  if (unchecked.length) {
    console.log(`  no parser here for: ${unchecked.sort((a, b) => b[1] - a[1]).map(([ext, n]) => `.${ext} (${n})`).join(', ')}`);
  }
  const broken = total - ok - unresolved;
  console.log(`\n${ok}/${total} of the snippets a parser exists for on this machine parse on their own.`);
  if (unresolved) console.log(`${unresolved} more parse but reference a sibling snippet they were not given.`);
  console.log(`${broken} genuinely do not parse — ${Math.round((broken / Math.max(1, total)) * 1000) / 10}% of what was checked.`);

  await rm(dir, { recursive: true, force: true });

  /* A floor, not a demand for perfection. The two C snippets that use errno
   * without including errno.h are left in on purpose — this is training text
   * for a model that learns characters, and hand-fixing what the agents wrote
   * would make the corpus something other than what the agents wrote. But a
   * build that dropped to four snippets in five has broken something, and
   * printing that in a report nobody reads is not a check. */
  const FLOOR = 0.9;
  const rate = total ? ok / total : 1;
  if (rate < FLOOR) {
    console.error(`\n✗ below the ${Math.round(FLOOR * 100)}% floor — something in the corpus or in the splitter is broken`);
    process.exitCode = 1;
  }
  return results;
}

const from = arg('from');
if (from) await build(from);
if (process.argv.includes('--verify')) await verify();
if (process.argv.includes('--audit')) await audit();
if (!from && !process.argv.includes('--verify') && !process.argv.includes('--audit')) {
  console.log('usage: node tools/lm-corpus.mjs --from <dir> | --verify | --audit');
}
