/* src/plan/moves.js — MOVES — the movement library
 *
 * One of the files index.html loads, in order, as plain classic scripts:
 * together they share a single global scope, exactly as the one file they
 * were split out of did. Order is load-bearing; see index.html.
 */
"use strict";
/* ---- movement library — calisthenics only -----------------------------
   Nothing here needs a dumbbell, a barbell or a machine. The kit it can ask
   for is the calisthenics kit: a pull-up bar, dip bars, rings, bands, an ab
   wheel, and added weight for weighted pull-ups and dips. Most of it needs a
   floor and a wall.
   b    = stable key — matches EXIMG when a clip exists, and what the log files under
   n/ns = what the user reads in Hebrew / Spanish (b doubles as the English name)
   pri  = the muscle it is chosen for; sec = what else it hits
   need = kit; each inner array is one set of interchangeable options
   lvl  = the lowest level it should be offered at                          */
const MOVES=[
{b:'Wall push-ups', n:'שכיבות סמיכה לקיר', ns:'Flexiones en la pared', m:'Reps', pri:'chest', sec:["triceps", "shoulders"], need:[], lvl:1, anim:'press', env:'bw'},
{b:'Incline push-ups', n:'שכיבות סמיכה בשיפוע (ידיים גבוה)', ns:'Flexiones inclinadas (manos altas)', m:'Reps', pri:'chest', sec:["triceps", "shoulders"], need:[], lvl:1, anim:'press', env:'bw'},
{b:'Knee push-ups', n:'שכיבות סמיכה על הברכיים', ns:'Flexiones de rodillas', m:'Reps', pri:'chest', sec:["triceps"], need:[], lvl:1, anim:'press', env:'bw'},
{b:'Push-ups', n:'שכיבות סמיכה', ns:'Flexiones', m:'Reps', pri:'chest', sec:["triceps", "shoulders"], need:[], lvl:2, anim:'press', env:'bw'},
{b:'Wide push-ups', n:'שכיבות סמיכה רחבות', ns:'Flexiones abiertas', m:'Reps', pri:'chest', sec:["shoulders"], need:[], lvl:2, anim:'press', env:'bw'},
{b:'Decline push-ups', n:'שכיבות סמיכה ברגליים מוגבהות', ns:'Flexiones con pies elevados', m:'Reps', pri:'chest', sec:["shoulders", "triceps"], need:[], lvl:3, anim:'press', env:'bw'},
{b:'Ring push-ups', n:'שכיבות סמיכה בטבעות', ns:'Flexiones en anillas', m:'Reps', pri:'chest', sec:["triceps", "core"], need:[["rings"]], lvl:5, anim:'press', env:'bw'},
{b:'Pseudo planche push-ups', n:'שכיבות פלאנש (ידיים לאגן)', ns:'Flexiones pseudo plancha', m:'Reps', pri:'chest', sec:["shoulders", "core"], need:[], lvl:5, anim:'press', env:'bw'},
{b:'Archer push-ups', n:'שכיבות סמיכה קשת', ns:'Flexiones de arquero', m:'Reps', pri:'chest', sec:["triceps"], need:[], lvl:6, anim:'press', env:'bw'},
{b:'Explosive push-ups', n:'שכיבות נפץ (מחיאת כף)', ns:'Flexiones explosivas', m:'Reps', pri:'chest', sec:["triceps", "shoulders"], need:[], lvl:6, anim:'press', env:'bw'},
{b:'One-arm push-up negative', n:'שכיבת יד אחת — ירידה בשליטה', ns:'Flexión a una mano (negativa)', m:'Reps', pri:'chest', sec:["triceps", "core"], need:[], lvl:8, anim:'press', env:'bw'},
{b:'One-arm push-up', n:'שכיבת סמיכה על יד אחת', ns:'Flexión a una mano', m:'Reps', pri:'chest', sec:["triceps", "core"], need:[], lvl:9, anim:'press', env:'bw'},
{b:'Dips', n:'מקבילים', ns:'Fondos en paralelas', m:'Reps', pri:'chest', sec:["triceps", "shoulders"], need:[["dip"]], lvl:4, anim:'press', env:'bw'},
{b:'Ring dips', n:'מקבילים בטבעות', ns:'Fondos en anillas', m:'Reps', pri:'chest', sec:["triceps", "shoulders"], need:[["rings"]], lvl:7, anim:'press', env:'bw'},
{b:'Prone Y raise', n:'הרמות Y בשכיבה על הבטן', ns:'Elevación en Y boca abajo', m:'Reps', pri:'back', sec:["shoulders"], need:[], lvl:1, anim:'pull', env:'bw'},
{b:'Reverse snow angel', n:'מלאך שלג הפוך', ns:'Ángel de nieve invertido', m:'Reps', pri:'back', sec:["shoulders"], need:[], lvl:1, anim:'pull', env:'bw'},
{b:'Superman', n:'סופרמן — הרמת גו', ns:'Superman', m:'Reps', pri:'back', sec:["glutes"], need:[], lvl:1, anim:'pull', env:'bw'},
{b:'Towel row', n:'חתירה במגבת מול משקוף', ns:'Remo con toalla en el marco', m:'Reps', pri:'back', sec:["biceps"], need:[], lvl:1, anim:'pull', env:'bw'},
{b:'Table row', n:'חתירה מתחת לשולחן', ns:'Remo bajo la mesa', m:'Reps', pri:'back', sec:["biceps"], need:[], lvl:1, anim:'pull', env:'bw'},
{b:'Band row', n:'חתירה בגומיית התנגדות', ns:'Remo con banda elástica', m:'Reps', pri:'back', sec:["biceps"], need:[["bands"]], lvl:1, anim:'pull', env:'bw'},
{b:'Scapular pull-ups', n:'משיכות שכמות בתלייה', ns:'Dominadas escapulares', m:'Reps', pri:'back', sec:[], need:[["bar"]], lvl:2, anim:'pull', env:'bw'},
{b:'Ring row', n:'חתירה בטבעות', ns:'Remo en anillas', m:'Reps', pri:'back', sec:["biceps"], need:[["rings"]], lvl:2, anim:'pull', env:'bw'},
{b:'Inverted row', n:'חתירה הפוכה (גוף תלוי)', ns:'Remo invertido', m:'Reps', pri:'back', sec:["biceps"], need:[["bar"]], lvl:2, anim:'pull', env:'bw'},
{b:'Assisted pull-ups', n:'מתח בסיוע גומייה', ns:'Dominadas asistidas con banda', m:'Reps', pri:'back', sec:["biceps"], need:[["bar"], ["bands"]], lvl:2, anim:'pull', env:'bw'},
{b:'Feet-elevated inverted row', n:'חתירה הפוכה ברגליים מוגבהות', ns:'Remo invertido con pies elevados', m:'Reps', pri:'back', sec:["biceps"], need:[["bar"]], lvl:3, anim:'pull', env:'bw'},
{b:'Negative pull-ups', n:'מתח — ירידה איטית בשליטה', ns:'Dominadas negativas', m:'Reps', pri:'back', sec:["biceps"], need:[["bar"]], lvl:3, anim:'pull', env:'bw'},
{b:'Pull-ups', n:'מתח באחיזה עליונה', ns:'Dominadas pronas', m:'Reps', pri:'back', sec:["biceps"], need:[["bar"]], lvl:4, anim:'pull', env:'bw'},
{b:'Chin-ups', n:'מתח באחיזה תחתונה', ns:'Dominadas supinas', m:'Reps', pri:'back', sec:["biceps"], need:[["bar"]], lvl:4, anim:'pull', env:'bw'},
{b:'Wide pull-ups', n:'מתח באחיזה רחבה', ns:'Dominadas agarre ancho', m:'Reps', pri:'back', sec:["biceps"], need:[["bar"]], lvl:5, anim:'pull', env:'bw'},
{b:'Skin the cat', n:'סקין דה קאט', ns:'Skin the cat', m:'Reps', pri:'back', sec:["core", "shoulders"], need:[["rings", "bar"]], lvl:6, anim:'pull', env:'bw'},
{b:'Archer pull-ups', n:'מתח קשת', ns:'Dominadas de arquero', m:'Reps', pri:'back', sec:["biceps"], need:[["bar"]], lvl:7, anim:'pull', env:'bw'},
{b:'Front lever tuck', n:'פרונט לוור מכווץ', ns:'Front lever agrupado', m:'Time', pri:'back', sec:["core"], need:[["bar", "rings"]], lvl:7, anim:'pull', env:'bw'},
{b:'Muscle-up negative', n:'מאסל אפ — ירידה בשליטה', ns:'Muscle-up negativo', m:'Reps', pri:'back', sec:["chest", "triceps"], need:[["bar"]], lvl:8, anim:'pull', env:'bw'},
{b:'Advanced tuck front lever', n:'פרונט לוור מכווץ פתוח', ns:'Front lever agrupado avanzado', m:'Time', pri:'back', sec:["core"], need:[["bar", "rings"]], lvl:8, anim:'pull', env:'bw'},
{b:'Muscle-up', n:'מאסל אפ', ns:'Muscle-up', m:'Reps', pri:'back', sec:["chest", "triceps"], need:[["bar"]], lvl:9, anim:'pull', env:'bw'},
{b:'Straddle front lever', n:'פרונט לוור פישוק', ns:'Front lever en straddle', m:'Time', pri:'back', sec:["core"], need:[["bar", "rings"]], lvl:9, anim:'pull', env:'bw'},
{b:'Front lever', n:'פרונט לוור מלא', ns:'Front lever completo', m:'Time', pri:'back', sec:["core"], need:[["bar", "rings"]], lvl:10, anim:'pull', env:'bw'},
{b:'Wall slide', n:'החלקת זרועות על הקיר', ns:'Deslizamiento de brazos en la pared', m:'Reps', pri:'shoulders', sec:["back"], need:[], lvl:1, anim:'press', env:'bw'},
{b:'Prone T raise', n:'הרמות T בשכיבה על הבטן', ns:'Elevación en T boca abajo', m:'Reps', pri:'shoulders', sec:["back"], need:[], lvl:1, anim:'press', env:'bw'},
{b:'Band lateral raise', n:'הרחקות צד בגומייה', ns:'Elevaciones laterales con banda', m:'Reps', pri:'shoulders', sec:[], need:[["bands"]], lvl:1, anim:'press', env:'bw'},
{b:'Band face pull', n:'משיכת פנים בגומייה', ns:'Face pull con banda', m:'Reps', pri:'shoulders', sec:["back"], need:[["bands"]], lvl:1, anim:'pull', env:'bw'},
{b:'Pike push-ups', n:'שכיבות פייק (כתפיים)', ns:'Flexiones pike', m:'Reps', pri:'shoulders', sec:["triceps"], need:[], lvl:2, anim:'press', env:'bw'},
{b:'Bear crawl shoulder tap', n:'זחילת דוב עם נגיעה בכתף', ns:'Marcha de oso con toque de hombro', m:'Time', pri:'shoulders', sec:["core"], need:[], lvl:2, anim:'press', env:'bw'},
{b:'Elevated pike push-ups', n:'שכיבות פייק ברגליים מוגבהות', ns:'Flexiones pike con pies elevados', m:'Reps', pri:'shoulders', sec:["triceps"], need:[], lvl:4, anim:'press', env:'bw'},
{b:'Wall handstand hold', n:'עמידת ידיים נשענת לקיר', ns:'Pino apoyado en la pared', m:'Time', pri:'shoulders', sec:["core", "triceps"], need:[], lvl:5, anim:'press', env:'bw'},
{b:'Wall handstand walk', n:'טיפוס רגליים על הקיר', ns:'Subida de pies por la pared', m:'Reps', pri:'shoulders', sec:["core", "triceps"], need:[], lvl:6, anim:'press', env:'bw'},
{b:'Wall handstand push-up negative', n:'עמידת ידיים — ירידה בשליטה', ns:'Flexión en pino (negativa)', m:'Reps', pri:'shoulders', sec:["triceps"], need:[], lvl:6, anim:'press', env:'bw'},
{b:'Wall handstand push-ups', n:'שכיבות בעמידת ידיים לקיר', ns:'Flexiones en pino en la pared', m:'Reps', pri:'shoulders', sec:["triceps"], need:[], lvl:7, anim:'press', env:'bw'},
{b:'Freestanding handstand', n:'עמידת ידיים חופשית', ns:'Pino libre', m:'Time', pri:'shoulders', sec:["core"], need:[], lvl:8, anim:'press', env:'bw'},
{b:'Freestanding handstand push-ups', n:'שכיבות בעמידת ידיים חופשית', ns:'Flexiones en pino libre', m:'Reps', pri:'shoulders', sec:["triceps", "core"], need:[], lvl:10, anim:'press', env:'bw'},
{b:'Self-resisted curl', n:'כפיפת מרפקים בהתנגדות עצמית', ns:'Curl con autorresistencia', m:'Reps', pri:'biceps', sec:[], need:[], lvl:1, anim:'pull', env:'bw'},
{b:'Towel curl', n:'כפיפת מרפקים במגבת (איזומטרי)', ns:'Curl isométrico con toalla', m:'Time', pri:'biceps', sec:[], need:[], lvl:1, anim:'pull', env:'bw'},
{b:'Band curl', n:'כפיפת מרפקים בגומייה', ns:'Curl de bíceps con banda', m:'Reps', pri:'biceps', sec:[], need:[["bands"]], lvl:1, anim:'pull', env:'bw'},
{b:'Doorway curl', n:'כפיפת מרפקים במשקוף', ns:'Curl en el marco de la puerta', m:'Reps', pri:'biceps', sec:[], need:[], lvl:2, anim:'pull', env:'bw'},
{b:'Underhand inverted row', n:'חתירה הפוכה באחיזה תחתונה', ns:'Remo invertido supino', m:'Reps', pri:'biceps', sec:["back"], need:[["bar"]], lvl:2, anim:'pull', env:'bw'},
{b:'Ring curl', n:'כפיפת מרפקים בטבעות (משקל גוף)', ns:'Curl en anillas', m:'Reps', pri:'biceps', sec:[], need:[["rings"]], lvl:4, anim:'pull', env:'bw'},
{b:'Bar curl', n:'כפיפת מרפקים על מוט נמוך', ns:'Curl en barra baja', m:'Reps', pri:'biceps', sec:[], need:[["bar"]], lvl:5, anim:'pull', env:'bw'},
{b:'Archer chin-ups', n:'מתח קשת באחיזה תחתונה', ns:'Dominadas supinas de arquero', m:'Reps', pri:'biceps', sec:["back"], need:[["bar"]], lvl:7, anim:'pull', env:'bw'},
{b:'One-arm chin-up negative', n:'מתח יד אחת — ירידה בשליטה', ns:'Dominada a un brazo (negativa)', m:'Reps', pri:'biceps', sec:["back"], need:[["bar"]], lvl:9, anim:'pull', env:'bw'},
{b:'Bench dips', n:'מקבילים על ספסל/כיסא', ns:'Fondos en banco o silla', m:'Reps', pri:'triceps', sec:["chest"], need:[], lvl:1, anim:'press', env:'bw'},
{b:'Band pushdown', n:'פשיטת מרפקים בגומייה', ns:'Extensión de tríceps con banda', m:'Reps', pri:'triceps', sec:[], need:[["bands"]], lvl:1, anim:'press', env:'bw'},
{b:'Close-grip push-ups', n:'שכיבות סמיכה באחיזה צרה', ns:'Flexiones agarre cerrado', m:'Reps', pri:'triceps', sec:["chest"], need:[], lvl:2, anim:'press', env:'bw'},
{b:'Diamond push-ups', n:'שכיבות יהלום', ns:'Flexiones diamante', m:'Reps', pri:'triceps', sec:["chest"], need:[], lvl:3, anim:'press', env:'bw'},
{b:'Bodyweight skull crusher', n:'סקאל קראשר משקל גוף (על שולחן)', ns:'Extensión de tríceps en mesa', m:'Reps', pri:'triceps', sec:[], need:[], lvl:4, anim:'press', env:'bw'},
{b:'Bar triceps extension', n:'פשיטת מרפקים על מוט נמוך', ns:'Extensión de tríceps en barra', m:'Reps', pri:'triceps', sec:[], need:[["bar"]], lvl:5, anim:'press', env:'bw'},
{b:'Ring triceps extension', n:'פשיטת מרפקים בטבעות', ns:'Extensión de tríceps en anillas', m:'Reps', pri:'triceps', sec:["core"], need:[["rings"]], lvl:6, anim:'press', env:'bw'},
{b:'Korean dips', n:'מקבילים קוריאניים', ns:'Fondos coreanos', m:'Reps', pri:'triceps', sec:["chest"], need:[["dip"]], lvl:8, anim:'press', env:'bw'},
{b:'Chair squat', n:'סקוואט לכיסא', ns:'Sentadilla a la silla', m:'Reps', pri:'quads', sec:["glutes"], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Bodyweight squat', n:'סקוואט משקל גוף', ns:'Sentadilla con peso corporal', m:'Reps', pri:'quads', sec:["glutes", "core"], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Wall sit', n:'ישיבת קיר', ns:'Sentadilla isométrica en la pared', m:'Time', pri:'quads', sec:[], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Step-up', n:'עליות מדרגה', ns:'Subida al cajón', m:'Reps', pri:'quads', sec:["glutes"], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Split squats', n:'סקוואט מפוצל', ns:'Sentadilla dividida', m:'Reps', pri:'quads', sec:["glutes"], need:[], lvl:2, anim:'squat', env:'bw'},
{b:'Walking lunge', n:'לאנג׳ הליכה', ns:'Zancada caminando', m:'Reps', pri:'quads', sec:["glutes", "hamstrings"], need:[], lvl:2, anim:'squat', env:'bw'},
{b:'Jump squat', n:'סקוואט קפיצה', ns:'Sentadilla con salto', m:'Reps', pri:'quads', sec:["glutes", "calves"], need:[], lvl:3, anim:'squat', env:'bw'},
{b:'Bulgarian split squat', n:'סקוואט בולגרי', ns:'Sentadilla búlgara', m:'Reps', pri:'quads', sec:["glutes"], need:[], lvl:5, anim:'squat', env:'bw'},
{b:'Cossack squat', n:'סקוואט קוזק', ns:'Sentadilla cosaca', m:'Reps', pri:'quads', sec:["glutes"], need:[], lvl:5, anim:'squat', env:'bw'},
{b:'Box pistol squat', n:'פיסטול לתיבה', ns:'Sentadilla pistol al cajón', m:'Reps', pri:'quads', sec:["glutes", "core"], need:[], lvl:5, anim:'squat', env:'bw'},
{b:'Assisted pistol squat', n:'פיסטול בסיוע', ns:'Sentadilla pistol asistida', m:'Reps', pri:'quads', sec:["glutes", "core"], need:[], lvl:6, anim:'squat', env:'bw'},
{b:'Shrimp squat', n:'סקוואט שרימפ', ns:'Sentadilla shrimp', m:'Reps', pri:'quads', sec:["glutes"], need:[], lvl:7, anim:'squat', env:'bw'},
{b:'Pistol squat', n:'סקוואט על רגל אחת (פיסטול)', ns:'Sentadilla a una pierna (pistol)', m:'Reps', pri:'quads', sec:["glutes", "core"], need:[], lvl:8, anim:'squat', env:'bw'},
{b:'Glute bridge march', n:'גשר ישבן עם הרמת רגל', ns:'Puente de glúteo con marcha', m:'Reps', pri:'hamstrings', sec:["glutes", "core"], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Hamstring walkout', n:'הליכת עקבים (המסטרינג)', ns:'Caminata de talones', m:'Reps', pri:'hamstrings', sec:["glutes"], need:[], lvl:2, anim:'squat', env:'bw'},
{b:'Single-leg hip hinge', n:'הינג׳ ירך על רגל אחת', ns:'Bisagra de cadera a una pierna', m:'Reps', pri:'hamstrings', sec:["glutes", "core"], need:[], lvl:3, anim:'squat', env:'bw'},
{b:'Sliding leg curl', n:'כפיפת ברך בהחלקה על הרצפה', ns:'Curl femoral deslizante', m:'Reps', pri:'hamstrings', sec:["glutes"], need:[], lvl:3, anim:'squat', env:'bw'},
{b:'Band leg curl', n:'כפיפת ברך בגומייה', ns:'Curl femoral con banda', m:'Reps', pri:'hamstrings', sec:[], need:[["bands"]], lvl:2, anim:'squat', env:'bw'},
{b:'Nordic curl negative', n:'נורדיק קרל (ירידה בשליטה)', ns:'Curl nórdico (negativa)', m:'Reps', pri:'hamstrings', sec:["glutes"], need:[], lvl:6, anim:'squat', env:'bw'},
{b:'Nordic curl', n:'נורדיק קרל מלא', ns:'Curl nórdico completo', m:'Reps', pri:'hamstrings', sec:["glutes"], need:[], lvl:9, anim:'squat', env:'bw'},
{b:'Glute bridge', n:'גשר ישבן', ns:'Puente de glúteo', m:'Reps', pri:'glutes', sec:["hamstrings"], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Frog pump', n:'פרוג פאמפ', ns:'Frog pump', m:'Reps', pri:'glutes', sec:[], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Fire hydrant', n:'ברז כיבוי (הרחקת ירך)', ns:'Abducción de cadera (fire hydrant)', m:'Reps', pri:'glutes', sec:[], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Donkey kick', n:'בעיטת חמור', ns:'Patada de glúteo', m:'Reps', pri:'glutes', sec:["hamstrings"], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Reverse hyperextension', n:'הרמת רגליים בשכיבה על הבטן', ns:'Hiperextensión inversa', m:'Reps', pri:'glutes', sec:["hamstrings", "back"], need:[], lvl:2, anim:'squat', env:'bw'},
{b:'Band kickback', n:'בעיטה אחורית בגומייה', ns:'Patada de glúteo con banda', m:'Reps', pri:'glutes', sec:["hamstrings"], need:[["bands"]], lvl:1, anim:'squat', env:'bw'},
{b:'Single-leg glute bridge', n:'גשר ישבן על רגל אחת', ns:'Puente de glúteo a una pierna', m:'Reps', pri:'glutes', sec:["hamstrings", "core"], need:[], lvl:3, anim:'squat', env:'bw'},
{b:'Elevated single-leg hip thrust', n:'היפ ת׳רסט על רגל אחת בהגבהה', ns:'Hip thrust a una pierna elevado', m:'Reps', pri:'glutes', sec:["hamstrings"], need:[], lvl:4, anim:'squat', env:'bw'},
{b:'Calf raise', n:'הרמות עקב בעמידה', ns:'Elevación de talones de pie', m:'Reps', pri:'calves', sec:[], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Calf raise on stairs', n:'הרמות עקב על מדרגה', ns:'Elevación de talones en escalón', m:'Reps', pri:'calves', sec:[], need:[], lvl:1, anim:'squat', env:'bw'},
{b:'Calf hops', n:'קפיצות שוק במקום', ns:'Saltos de gemelo', m:'Reps', pri:'calves', sec:[], need:[], lvl:2, anim:'squat', env:'bw'},
{b:'Single-leg calf raise', n:'הרמות עקב על רגל אחת', ns:'Elevación de talones a una pierna', m:'Reps', pri:'calves', sec:[], need:[], lvl:2, anim:'squat', env:'bw'},
{b:'Single-leg calf raise on stairs', n:'הרמות עקב על רגל אחת ממדרגה', ns:'Elevación a una pierna en escalón', m:'Reps', pri:'calves', sec:[], need:[], lvl:4, anim:'squat', env:'bw'},
{b:'Dead bug', n:'דד באג', ns:'Dead bug', m:'Reps', pri:'core', sec:[], need:[], lvl:1, anim:'core', env:'bw'},
{b:'Knee plank', n:'פלאנק על הברכיים', ns:'Plancha de rodillas', m:'Time', pri:'core', sec:[], need:[], lvl:1, anim:'core', env:'bw'},
{b:'Static plank', n:'פלאנק', ns:'Plancha', m:'Time', pri:'core', sec:[], need:[], lvl:1, anim:'core', env:'bw'},
{b:'Crunches', n:'כפיפות בטן', ns:'Encogimientos abdominales', m:'Reps', pri:'core', sec:[], need:[], lvl:1, anim:'core', env:'bw'},
{b:'Bicycle crunch', n:'אופני אוויר', ns:'Bicicleta abdominal', m:'Reps', pri:'core', sec:[], need:[], lvl:1, anim:'core', env:'bw'},
{b:'Mountain climber', n:'הרים מטפסים', ns:'Escaladores', m:'Time', pri:'core', sec:["quads"], need:[], lvl:1, anim:'core', env:'bw'},
{b:'Side plank', n:'פלאנק צד', ns:'Plancha lateral', m:'Time', pri:'core', sec:[], need:[], lvl:2, anim:'core', env:'bw'},
{b:'Leg raise', n:'הרמות רגליים בשכיבה', ns:'Elevación de piernas tumbado', m:'Reps', pri:'core', sec:[], need:[], lvl:2, anim:'core', env:'bw'},
{b:'Russian twist', n:'סיבובים רוסיים', ns:'Giro ruso', m:'Reps', pri:'core', sec:[], need:[], lvl:2, anim:'core', env:'bw'},
{b:'Hollow hold', n:'הולו הולד', ns:'Hollow hold', m:'Time', pri:'core', sec:[], need:[], lvl:3, anim:'core', env:'bw'},
{b:'Hollow rock', n:'הולו רוק', ns:'Hollow rock', m:'Reps', pri:'core', sec:[], need:[], lvl:4, anim:'core', env:'bw'},
{b:'V-up', n:'וי-אפ', ns:'V-up', m:'Reps', pri:'core', sec:[], need:[], lvl:4, anim:'core', env:'bw'},
{b:'Hanging knee raise', n:'הרמות ברכיים בתלייה', ns:'Elevación de rodillas colgado', m:'Reps', pri:'core', sec:[], need:[["bar"]], lvl:4, anim:'core', env:'bw'},
{b:'Tuck L-sit', n:'אל-סיט מכווץ', ns:'L-sit agrupado', m:'Time', pri:'core', sec:["triceps"], need:[], lvl:5, anim:'core', env:'bw'},
{b:'Ab wheel rollout', n:'גלגל בטן', ns:'Rueda abdominal', m:'Reps', pri:'core', sec:[], need:[["abwheel"]], lvl:6, anim:'core', env:'bw'},
{b:'Hanging leg raise', n:'הרמות רגליים בתלייה', ns:'Elevación de piernas colgado', m:'Reps', pri:'core', sec:[], need:[["bar"]], lvl:6, anim:'core', env:'bw'},
{b:'L-sit', n:'אל-סיט מלא', ns:'L-sit completo', m:'Time', pri:'core', sec:["triceps"], need:[["dip"]], lvl:7, anim:'core', env:'bw'},
{b:'Toes to bar', n:'אצבעות למוט', ns:'Pies a la barra', m:'Reps', pri:'core', sec:[], need:[["bar"]], lvl:7, anim:'core', env:'bw'},
{b:'Dragon flag negative', n:'דרגון פלאג — ירידה בשליטה', ns:'Dragon flag negativa', m:'Reps', pri:'core', sec:[], need:[], lvl:8, anim:'core', env:'bw'},
{b:'Windshield wipers', n:'מגבים בתלייה', ns:'Limpiaparabrisas colgado', m:'Reps', pri:'core', sec:[], need:[["bar"]], lvl:8, anim:'core', env:'bw'},
{b:'Dragon flag', n:'דרגון פלאג', ns:'Dragon flag', m:'Reps', pri:'core', sec:[], need:[], lvl:10, anim:'core', env:'bw'},
{b:'Front lever pull-ups', n:'מתח בפרונט לוור', ns:'Dominadas en front lever', m:'Reps', pri:'back', sec:["core"], need:[["bar"]], lvl:10, anim:'pull', env:'bw'},
{b:'L-sit to handstand', n:'אל-סיט לעמידת ידיים', ns:'L-sit a pino', m:'Reps', pri:'shoulders', sec:["core","triceps"], need:[["dip"]], lvl:10, anim:'press', env:'bw'},
{b:"Machine chest press", n:"מכונת לחיצת חזה", ns:"Press de pecho en máquina", m:"משקל 🏋️", pri:"chest", sec:["triceps", "shoulders"], need:[["machines"]], lvl:1, anim:"press", env:"gym"},
{b:"Dumbbell bench press", n:"לחיצת חזה בשכיבה עם משקולות יד", ns:"Press de banca con mancuernas", m:"משקל 🏋️", pri:"chest", sec:["triceps", "shoulders"], need:[["dumbbells"], ["bench"]], lvl:2, anim:"press", env:"gym"},
{b:"Barbell bench press", n:"לחיצת חזה במוט", ns:"Press de banca con barra", m:"משקל 🏋️", pri:"chest", sec:["triceps", "shoulders"], need:[["barbell"], ["bench"]], lvl:3, anim:"press", env:"gym"},
{b:"Dumbbell incline press", n:"לחיצת חזה בשיפוע עם משקולות יד", ns:"Press inclinado con mancuernas", m:"משקל 🏋️", pri:"chest", sec:["shoulders", "triceps"], need:[["dumbbells"], ["bench"]], lvl:3, anim:"press", env:"gym"},
{b:"Cable chest fly", n:"פרפר בכבלים", ns:"Aperturas en polea", m:"משקל 🏋️", pri:"chest", sec:["shoulders"], need:[["cables"]], lvl:2, anim:"press", env:"gym"},
{b:"Dumbbell fly", n:"פרפר עם משקולות יד", ns:"Aperturas con mancuernas", m:"משקל 🏋️", pri:"chest", sec:["shoulders"], need:[["dumbbells"], ["bench"]], lvl:3, anim:"press", env:"gym"},
{b:"Decline barbell press", n:"לחיצת חזה בשיפוע שלילי", ns:"Press declinado con barra", m:"משקל 🏋️", pri:"chest", sec:["triceps"], need:[["barbell"], ["bench"]], lvl:5, anim:"press", env:"gym"},
{b:"Weighted dips", n:"מקבילים במשקל נוסף", ns:"Fondos con lastre", m:"משקל 🏋️", pri:"chest", sec:["triceps", "shoulders"], need:[["dip"], ["weight"]], lvl:6, anim:"press", env:"gym"},
{b:"Machine pec deck", n:"מכונת פק-דק", ns:"Contractora de pecho", m:"משקל 🏋️", pri:"chest", sec:["shoulders"], need:[["machines"]], lvl:1, anim:"press", env:"gym"},
{b:"Dumbbell floor press", n:"לחיצת חזה על הרצפה עם משקולות", ns:"Press de pecho en el suelo", m:"משקל 🏋️", pri:"chest", sec:["triceps"], need:[["dumbbells"]], lvl:1, anim:"press", env:"gym"},
{b:"Barbell floor press", n:"לחיצת חזה על הרצפה במוט", ns:"Press de suelo con barra", m:"משקל 🏋️", pri:"chest", sec:["triceps"], need:[["barbell"]], lvl:3, anim:"press", env:"gym"},
{b:"Lat pulldown", n:"פולי עליון", ns:"Jalón al pecho", m:"משקל 🏋️", pri:"back", sec:["biceps"], need:[["machines", "cables"]], lvl:1, anim:"pull", env:"gym"},
{b:"Seated cable row", n:"חתירה בכבל בישיבה", ns:"Remo sentado en polea", m:"משקל 🏋️", pri:"back", sec:["biceps"], need:[["cables", "machines"]], lvl:1, anim:"pull", env:"gym"},
{b:"Machine row", n:"מכונת חתירה", ns:"Remo en máquina", m:"משקל 🏋️", pri:"back", sec:["biceps"], need:[["machines"]], lvl:1, anim:"pull", env:"gym"},
{b:"One-arm dumbbell row", n:"חתירה עם משקולת יד אחת", ns:"Remo a una mano con mancuerna", m:"משקל 🏋️", pri:"back", sec:["biceps"], need:[["dumbbells"]], lvl:2, anim:"pull", env:"gym"},
{b:"Dumbbell row", n:"חתירה עם משקולות יד", ns:"Remo con mancuernas", m:"משקל 🏋️", pri:"back", sec:["biceps"], need:[["dumbbells"]], lvl:2, anim:"pull", env:"gym"},
{b:"Barbell row", n:"חתירה במוט", ns:"Remo con barra", m:"משקל 🏋️", pri:"back", sec:["biceps", "hamstrings"], need:[["barbell"]], lvl:4, anim:"pull", env:"gym"},
{b:"Straight-arm pulldown", n:"משיכת פולי בידיים ישרות", ns:"Jalón con brazos rectos", m:"משקל 🏋️", pri:"back", sec:[], need:[["cables"]], lvl:2, anim:"pull", env:"gym"},
{b:"Weighted pull-up", n:"מתח במשקל נוסף", ns:"Dominada con lastre", m:"משקל 🏋️", pri:"back", sec:["biceps"], need:[["bar"], ["weight"]], lvl:7, anim:"pull", env:"gym"},
{b:"T-bar row", n:"חתירת טי-בר", ns:"Remo en T", m:"משקל 🏋️", pri:"back", sec:["biceps"], need:[["barbell", "machines"]], lvl:5, anim:"pull", env:"gym"},
{b:"Pendlay row", n:"חתירת פנדליי", ns:"Remo Pendlay", m:"משקל 🏋️", pri:"back", sec:["biceps", "hamstrings"], need:[["barbell"]], lvl:7, anim:"pull", env:"gym"},
{b:"Machine shoulder press", n:"מכונת לחיצת כתפיים", ns:"Press de hombro en máquina", m:"משקל 🏋️", pri:"shoulders", sec:["triceps"], need:[["machines"]], lvl:1, anim:"press", env:"gym"},
{b:"Dumbbell shoulder press", n:"לחיצת כתפיים עם משקולות יד", ns:"Press de hombro con mancuernas", m:"משקל 🏋️", pri:"shoulders", sec:["triceps"], need:[["dumbbells"]], lvl:2, anim:"press", env:"gym"},
{b:"Lateral raise", n:"הרחקות צד", ns:"Elevaciones laterales", m:"משקל 🏋️", pri:"shoulders", sec:[], need:[["dumbbells", "cables"]], lvl:1, anim:"press", env:"gym"},
{b:"Cable lateral raise", n:"הרחקות צד בכבל", ns:"Elevación lateral en polea", m:"משקל 🏋️", pri:"shoulders", sec:[], need:[["cables"]], lvl:2, anim:"press", env:"gym"},
{b:"Reverse fly", n:"פרפר הפוך", ns:"Aperturas invertidas", m:"משקל 🏋️", pri:"shoulders", sec:["back"], need:[["dumbbells", "cables"]], lvl:2, anim:"press", env:"gym"},
{b:"Face pull", n:"משיכת פנים בכבל", ns:"Face pull en polea", m:"משקל 🏋️", pri:"shoulders", sec:["back"], need:[["cables"]], lvl:2, anim:"pull", env:"gym"},
{b:"Barbell overhead press", n:"לחיצת כתפיים במוט בעמידה", ns:"Press militar con barra", m:"משקל 🏋️", pri:"shoulders", sec:["triceps", "core"], need:[["barbell"]], lvl:4, anim:"press", env:"gym"},
{b:"Arnold press", n:"לחיצת ארנולד", ns:"Press Arnold", m:"משקל 🏋️", pri:"shoulders", sec:["triceps"], need:[["dumbbells"]], lvl:5, anim:"press", env:"gym"},
{b:"Barbell upright row", n:"חתירה זקופה במוט", ns:"Remo al mentón con barra", m:"משקל 🏋️", pri:"shoulders", sec:["back"], need:[["barbell", "dumbbells"]], lvl:3, anim:"pull", env:"gym"},
{b:"Dumbbell curl", n:"כפיפת מרפקים עם משקולות יד", ns:"Curl con mancuernas", m:"משקל 🏋️", pri:"biceps", sec:[], need:[["dumbbells"]], lvl:1, anim:"pull", env:"gym"},
{b:"Barbell curl", n:"כפיפת מרפקים במוט", ns:"Curl con barra", m:"משקל 🏋️", pri:"biceps", sec:[], need:[["barbell"]], lvl:2, anim:"pull", env:"gym"},
{b:"Cable curl", n:"כפיפת מרפקים בכבל", ns:"Curl en polea", m:"משקל 🏋️", pri:"biceps", sec:[], need:[["cables"]], lvl:1, anim:"pull", env:"gym"},
{b:"Hammer curl", n:"כפיפת פטיש", ns:"Curl martillo", m:"משקל 🏋️", pri:"biceps", sec:[], need:[["dumbbells"]], lvl:2, anim:"pull", env:"gym"},
{b:"Incline dumbbell curl", n:"כפיפת מרפקים בשיפוע", ns:"Curl inclinado con mancuernas", m:"משקל 🏋️", pri:"biceps", sec:[], need:[["dumbbells"], ["bench"]], lvl:4, anim:"pull", env:"gym"},
{b:"Preacher curl", n:"כפיפת מרפקים על משענת", ns:"Curl predicador", m:"משקל 🏋️", pri:"biceps", sec:[], need:[["machines", "barbell"], ["bench"]], lvl:3, anim:"pull", env:"gym"},
{b:"Concentration curl", n:"כפיפת ריכוז", ns:"Curl de concentración", m:"משקל 🏋️", pri:"biceps", sec:[], need:[["dumbbells"]], lvl:3, anim:"pull", env:"gym"},
{b:"Machine curl", n:"מכונת כפיפת מרפקים", ns:"Curl en máquina", m:"משקל 🏋️", pri:"biceps", sec:[], need:[["machines"]], lvl:1, anim:"pull", env:"gym"},
{b:"Cable pushdown", n:"פשיטת מרפקים בכבל", ns:"Extensión de tríceps en polea", m:"משקל 🏋️", pri:"triceps", sec:[], need:[["cables"]], lvl:1, anim:"press", env:"gym"},
{b:"Machine triceps extension", n:"מכונת פשיטת מרפקים", ns:"Extensión de tríceps en máquina", m:"משקל 🏋️", pri:"triceps", sec:[], need:[["machines"]], lvl:1, anim:"press", env:"gym"},
{b:"Overhead dumbbell extension", n:"פשיטת מרפקים מעל הראש", ns:"Extensión de tríceps sobre la cabeza", m:"משקל 🏋️", pri:"triceps", sec:[], need:[["dumbbells"]], lvl:2, anim:"press", env:"gym"},
{b:"Skull crusher", n:"סקאל קראשר", ns:"Rompecráneos", m:"משקל 🏋️", pri:"triceps", sec:[], need:[["barbell", "dumbbells"]], lvl:4, anim:"press", env:"gym"},
{b:"Close-grip bench press", n:"לחיצת חזה באחיזה צרה", ns:"Press de banca agarre cerrado", m:"משקל 🏋️", pri:"triceps", sec:["chest"], need:[["barbell"], ["bench"]], lvl:4, anim:"press", env:"gym"},
{b:"Rope pushdown", n:"פשיטת מרפקים בחבל", ns:"Extensión con cuerda", m:"משקל 🏋️", pri:"triceps", sec:[], need:[["cables"]], lvl:1, anim:"press", env:"gym"},
{b:"Dumbbell kickback", n:"בעיטת טרייספס", ns:"Patada de tríceps", m:"משקל 🏋️", pri:"triceps", sec:[], need:[["dumbbells"]], lvl:2, anim:"press", env:"gym"},
{b:"Leg press", n:"מכונת לחיצת רגליים", ns:"Prensa de piernas", m:"משקל 🏋️", pri:"quads", sec:["glutes", "hamstrings"], need:[["machines"]], lvl:1, anim:"squat", env:"gym"},
{b:"Leg extension", n:"מכונת פשיטת ברך", ns:"Extensión de cuádriceps", m:"משקל 🏋️", pri:"quads", sec:[], need:[["machines"]], lvl:1, anim:"squat", env:"gym"},
{b:"Goblet squat", n:"סקוואט גובלט", ns:"Sentadilla goblet", m:"משקל 🏋️", pri:"quads", sec:["glutes", "core"], need:[["dumbbells", "kettlebell"]], lvl:2, anim:"squat", env:"gym"},
{b:"Dumbbell lunge", n:"לאנג׳ עם משקולות יד", ns:"Zancada con mancuernas", m:"משקל 🏋️", pri:"quads", sec:["glutes"], need:[["dumbbells"]], lvl:3, anim:"squat", env:"gym"},
{b:"Barbell squat", n:"סקוואט במוט", ns:"Sentadilla con barra", m:"משקל 🏋️", pri:"quads", sec:["glutes", "core"], need:[["barbell"]], lvl:4, anim:"squat", env:"gym"},
{b:"Hack squat", n:"האק סקוואט", ns:"Sentadilla hack", m:"משקל 🏋️", pri:"quads", sec:["glutes"], need:[["machines"]], lvl:3, anim:"squat", env:"gym"},
{b:"Front squat", n:"סקוואט קדמי", ns:"Sentadilla frontal", m:"משקל 🏋️", pri:"quads", sec:["core", "glutes"], need:[["barbell"]], lvl:6, anim:"squat", env:"gym"},
{b:"Dumbbell Bulgarian split squat", n:"סקוואט בולגרי עם משקולות", ns:"Sentadilla búlgara con mancuernas", m:"משקל 🏋️", pri:"quads", sec:["glutes"], need:[["dumbbells"], ["bench"]], lvl:5, anim:"squat", env:"gym"},
{b:"Lying leg curl", n:"מכונת כפיפת ברך בשכיבה", ns:"Curl femoral tumbado", m:"משקל 🏋️", pri:"hamstrings", sec:["calves"], need:[["machines"]], lvl:1, anim:"squat", env:"gym"},
{b:"Seated leg curl", n:"מכונת כפיפת ברך בישיבה", ns:"Curl femoral sentado", m:"משקל 🏋️", pri:"hamstrings", sec:[], need:[["machines"]], lvl:1, anim:"squat", env:"gym"},
{b:"Romanian deadlift", n:"דדליפט רומני", ns:"Peso muerto rumano", m:"משקל 🏋️", pri:"hamstrings", sec:["glutes", "back"], need:[["barbell", "dumbbells"]], lvl:3, anim:"squat", env:"gym"},
{b:"Dumbbell stiff-leg deadlift", n:"דדליפט רגליים ישרות עם משקולות", ns:"Peso muerto piernas rígidas", m:"משקל 🏋️", pri:"hamstrings", sec:["glutes"], need:[["dumbbells"]], lvl:2, anim:"squat", env:"gym"},
{b:"Cable pull-through", n:"משיכה בין הרגליים בכבל", ns:"Pull-through en polea", m:"משקל 🏋️", pri:"hamstrings", sec:["glutes"], need:[["cables"]], lvl:2, anim:"squat", env:"gym"},
{b:"Conventional deadlift", n:"דדליפט קלאסי", ns:"Peso muerto convencional", m:"משקל 🏋️", pri:"hamstrings", sec:["glutes", "back"], need:[["barbell"]], lvl:6, anim:"squat", env:"gym"},
{b:"Barbell hip thrust", n:"היפ ת׳רסט במוט", ns:"Hip thrust con barra", m:"משקל 🏋️", pri:"glutes", sec:["hamstrings"], need:[["barbell"], ["bench"]], lvl:3, anim:"squat", env:"gym"},
{b:"Cable kickback", n:"בעיטה אחורית בכבל", ns:"Patada de glúteo en polea", m:"משקל 🏋️", pri:"glutes", sec:["hamstrings"], need:[["cables"]], lvl:1, anim:"squat", env:"gym"},
{b:"Machine hip abduction", n:"מכונת פישוק ירכיים", ns:"Abductores en máquina", m:"משקל 🏋️", pri:"glutes", sec:[], need:[["machines"]], lvl:1, anim:"squat", env:"gym"},
{b:"Dumbbell step-up", n:"עלייה על ספסל עם משקולות", ns:"Subida al cajón con mancuernas", m:"משקל 🏋️", pri:"glutes", sec:["quads"], need:[["dumbbells"], ["bench"]], lvl:3, anim:"squat", env:"gym"},
{b:"Kettlebell swing", n:"סווינג קטלבל", ns:"Swing con kettlebell", m:"משקל 🏋️", pri:"glutes", sec:["hamstrings", "core"], need:[["kettlebell", "dumbbells"]], lvl:4, anim:"squat", env:"gym"},
{b:"Machine glute kickback", n:"מכונת בעיטת ישבן", ns:"Patada de glúteo en máquina", m:"משקל 🏋️", pri:"glutes", sec:["hamstrings"], need:[["machines"]], lvl:1, anim:"squat", env:"gym"},
{b:"Barbell glute bridge", n:"גשר ישבן במוט", ns:"Puente de glúteo con barra", m:"משקל 🏋️", pri:"glutes", sec:["hamstrings"], need:[["barbell"]], lvl:2, anim:"squat", env:"gym"},
{b:"Standing calf raise machine", n:"מכונת הרמות עקב בעמידה", ns:"Elevación de talones en máquina", m:"משקל 🏋️", pri:"calves", sec:[], need:[["machines"]], lvl:1, anim:"squat", env:"gym"},
{b:"Seated calf raise", n:"הרמות עקב בישיבה", ns:"Elevación de talones sentado", m:"משקל 🏋️", pri:"calves", sec:[], need:[["machines"]], lvl:1, anim:"squat", env:"gym"},
{b:"Dumbbell calf raise", n:"הרמות עקב עם משקולות יד", ns:"Elevación de talones con mancuernas", m:"משקל 🏋️", pri:"calves", sec:[], need:[["dumbbells"]], lvl:1, anim:"squat", env:"gym"},
{b:"Barbell calf raise", n:"הרמות עקב במוט", ns:"Elevación de talones con barra", m:"משקל 🏋️", pri:"calves", sec:[], need:[["barbell"]], lvl:3, anim:"squat", env:"gym"},
{b:"Leg press calf press", n:"לחיצת שוקיים במכונת רגליים", ns:"Elevación de talones en prensa", m:"משקל 🏋️", pri:"calves", sec:[], need:[["machines"]], lvl:2, anim:"squat", env:"gym"},
{b:"Cable crunch", n:"כפיפות בטן בכבל", ns:"Crunch en polea", m:"משקל 🏋️", pri:"core", sec:[], need:[["cables"]], lvl:2, anim:"core", env:"gym"},
{b:"Machine crunch", n:"מכונת כפיפות בטן", ns:"Crunch en máquina", m:"משקל 🏋️", pri:"core", sec:[], need:[["machines"]], lvl:1, anim:"core", env:"gym"},
{b:"Weighted plank", n:"פלאנק במשקל נוסף", ns:"Plancha con lastre", m:"Time", pri:"core", sec:[], need:[["weight"]], lvl:4, anim:"core", env:"gym"},
{b:"Dumbbell side bend", n:"כפיפות צד עם משקולת", ns:"Inclinación lateral con mancuerna", m:"משקל 🏋️", pri:"core", sec:[], need:[["dumbbells"]], lvl:1, anim:"core", env:"gym"},
{b:"Weighted decline sit-up", n:"כפיפות בטן בשיפוע עם משקל", ns:"Abdominal declinado con peso", m:"משקל 🏋️", pri:"core", sec:[], need:[["bench"], ["weight"]], lvl:3, anim:"core", env:"gym"},
{b:"Pallof press", n:"לחיצת פאלוף", ns:"Press Pallof", m:"Time", pri:"core", sec:["shoulders"], need:[["cables"]], lvl:2, anim:"core", env:"gym"},
{b:"Barbell rollout", n:"גלגול עם מוט", ns:"Rueda con barra", m:"Reps", pri:"core", sec:[], need:[["barbell"]], lvl:6, anim:"core", env:"gym"},
{b:"Weighted hanging leg raise", n:"הרמות רגליים בתלייה עם משקל", ns:"Elevación de piernas colgado con lastre", m:"משקל 🏋️", pri:"core", sec:[], need:[["bar"], ["weight"]], lvl:8, anim:"core", env:"gym"},
{b:"Farmer's carry", n:"הליכת החקלאי", ns:"Paseo del granjero", m:"משקל 🏋️", pri:"core", sec:["back"], need:[["dumbbells", "kettlebell"]], lvl:3, anim:"core", env:"gym"},
{b:"Captain's chair leg raise", n:"הרמות רגליים בכיסא רומי", ns:"Elevación de piernas en silla romana", m:"Reps", pri:"core", sec:[], need:[["machines"]], lvl:3, anim:"core", env:"gym"}
];

/* w=2 marks a multi-joint movement; those anchor a session, the rest fill it in.
   The gym half needs its own words — a bench press and a deadlift are compounds
   and none of the bodyweight vocabulary would have caught them. */
const COMPOUND_RX=/push-up|dip|pull-up|chin-up|row|squat|lunge|step-up|muscle-up|handstand|pike|lever|bridge|nordic|rollout|superman|skin the cat|hyperextension|walkout|thrust|press|deadlift|pulldown|swing|carry/i;
MOVES.forEach(function(mv){if(mv.w==null)mv.w=COMPOUND_RX.test(mv.b)?2:1;});
MOVE_W_FIX:{var _fix={'Scapular pull-ups':1,'Wall slide':1,'Prone T raise':1,'Prone Y raise':1,'Reverse snow angel':1,
  /* they say "press" or "pulldown" but they are single-joint */
  'Pallof press':1,'Leg press calf press':1,'Straight-arm pulldown':1,'Machine triceps extension':1};
  MOVES.forEach(function(mv){if(_fix[mv.b]!=null)mv.w=_fix[mv.b];});}
const MOVE_BY_BASE={};MOVES.forEach(function(x){MOVE_BY_BASE[x.b]=x;});

